<script setup>
import {ref,onMounted,onBeforeUnmount} from 'vue';
import {api,on,state,date} from './native.js';
import Icon from './Icon.vue';import AppOverlay from './AppOverlay.vue';import AppSelect from './AppSelect.vue';
defineProps({admin:Boolean});const emit=defineEmits(['navigate','changed']);
const items=ref([]),before=ref([]),more=ref(false),unread=ref(0),filter=ref('all'),busy=ref(false),error=ref(''),compose=ref(false),form=ref({title:'',body:'',all:false,recipients:''});let live=true;
async function load(){busy.value=true;error.value='';try{const r=await api('/api/inbox?unread='+(filter.value==='unread'?1:0)+(before.value.length?'&before='+before.value.at(-1):''));if(live){items.value=r.items;more.value=r.more;unread.value=r.unread;emit('changed');}}catch(e){if(live)error.value=e.message;}finally{if(live)busy.value=false;}}
async function read(item){try{await api('/api/inbox/read','POST',{id:item.id});emit('changed');if(item.target)emit('navigate',item.target);else await load();}catch(e){error.value=e.message;}}
async function all(){try{await api('/api/inbox/read','POST',{all:true});await load();}catch(e){error.value=e.message;}}
async function send(){if(busy.value)return;busy.value=true;try{await api('/api/admin/inbox/send','POST',{...form.value,id:crypto.randomUUID(),recipients:form.value.recipients.trim().split(/\s+/)});compose.value=false;form.value={title:'',body:'',all:false,recipients:''};await load();}catch(e){error.value=e.message;}finally{busy.value=false;}}
const stop=on('inbox-changed',()=>void load());onMounted(load);onBeforeUnmount(()=>{live=false;stop();});
</script>
<template><section class="content-page inbox-page"><div class="page-toolbar"><h1>收件箱</h1><button class="icon-button" aria-label="刷新收件箱" :disabled="busy" @click="load"><Icon name="refresh"/></button></div><section class="card form-stack"><div class="actions"><span class="tag">{{unread}} 条未读</span><button class="text-button" :disabled="busy||!unread" @click="all">全部已读</button><button v-if="admin" class="soft-button" @click="compose=true">发送站内信</button></div><AppSelect v-model="filter" label="消息范围" :options="[{value:'all',label:'全部消息'},{value:'unread',label:'仅未读'}]" @change="before=[];load()"/><p v-if="error" class="error-note" role="alert">{{error}}</p><div class="mobile-inbox-list"><button v-for="item in items" :key="item.id" class="mobile-inbox-message" :class="{unread:!item.readAt}" @click="read(item)"><div><strong>{{item.title}}</strong><time>{{date(item.created)}}</time></div><p>{{item.body}}</p><small>{{item.target?'查看内容':'站内消息'}}</small></button><p v-if="!busy&&!items.length" class="empty-note">{{state.connected?'收件箱已经看完了':'登录社区后查看收件箱'}}</p></div><div class="pagination"><button :disabled="busy||!before.length" @click="before.pop();load()">上一页</button><span>{{before.length+1}}</span><button :disabled="busy||!more" @click="before.push(items.at(-1).id);load()">下一页</button></div></section><AppOverlay :open="compose" label="发送站内信" @close="compose=false"><section class="sheet"><header class="sheet-header"><h2>发送站内信</h2><button class="icon-button" aria-label="关闭站内信" @click="compose=false"><Icon name="close"/></button></header><form class="sheet-body form-stack" @submit.prevent="send"><label>标题<input v-model="form.title" required maxlength="100"></label><label>正文<textarea v-model="form.body" required maxlength="2000" rows="5"/></label><AppSelect v-model="form.all" label="接收范围" :options="[{value:false,label:'指定成员'},{value:true,label:'全体成员'}]"/><label v-if="!form.all">成员 UUID（每行一个）<textarea v-model="form.recipients" required rows="3"/></label><p v-if="error" class="error-note">{{error}}</p><button class="primary" :disabled="busy">发送</button></form></section></AppOverlay></section></template>
<style>.mobile-inbox-list{display:grid;gap:10px}.mobile-inbox-message{display:block;width:100%;padding:14px;border:1px solid var(--line);border-radius:12px;background:transparent;text-align:left;color:inherit;overflow-wrap:anywhere}.mobile-inbox-message.unread{border-inline-start:3px solid var(--accent);background:var(--soft)}.mobile-inbox-message>div{display:flex;flex-wrap:wrap;gap:6px 12px;align-items:baseline}.mobile-inbox-message time,.mobile-inbox-message small{font-size:.78rem;color:var(--muted)}.mobile-inbox-message p{margin:10px 0;white-space:pre-wrap;line-height:1.6}</style>
