<script setup>
import {ref,onMounted,onBeforeUnmount} from 'vue';
import {api,native,state} from './native.js';
import Icon from './Icon.vue';
const items=ref([]),access=ref({}),grants=ref([]),uid=ref(''),name=ref(''),busy=ref(false),error=ref(''),notice=ref('');let timer;
async function refresh(){if(busy.value)return;busy.value=true;error.value='';try{const [a,r]=await Promise.all([api('/api/lobby/access'),api('/api/lobby/rooms')]);access.value=a;items.value=r.items||[];if(a.admin)grants.value=(await api('/api/admin/lobby/grants')).items||[];}catch(e){error.value=/404|Not Found/i.test(e.message)?'当前社区尚未启用直连房间扩展，请管理员安装 0.6.0 配套扩展。':e.message;}finally{busy.value=false;}}
async function copy(room){try{await native('clipboard',{text:room.invite});notice.value='邀请已复制，可在电脑启动器的联机大厅加入';}catch(e){error.value=e.message;}}
async function grant(id,remove=false){busy.value=true;try{await api('/api/admin/lobby/grants','POST',{uid:id,enabled:!remove});uid.value='';name.value='';}catch(e){error.value=e.message;}finally{busy.value=false;}if(!error.value)await refresh();}
onMounted(()=>{void refresh();timer=setInterval(()=>{if(!document.hidden)void refresh();},20000);});onBeforeUnmount(()=>clearInterval(timer));
</script>
<template><section class="content-page lobby-page"><div class="page-toolbar"><h1>MC 联机大厅</h1><button class="icon-button" aria-label="刷新联机房间" :disabled="busy" @click="refresh"><Icon name="refresh"/></button></div><p class="card muted">在手机查看房间与复制邀请；在电脑启动器中选择实例加入。游戏流量直接连接房主。</p><p v-if="error" class="card error-note" role="alert">{{error}}</p><p v-if="notice" class="card" role="status">{{notice}}</p><section class="card"><header class="mobile-card-heading"><h2>正在联机的房间</h2><span class="tag">{{items.length}}</span></header><p v-if="!items.length" class="empty-note">{{busy?'正在读取房间…':'暂时没有公开房间'}}</p><article v-for="r in items" :key="r.id" class="lobby-room"><div><h3>{{r.name}}</h3><p>{{r.owner}} · {{r.version||'版本待确认'}} {{r.loader}}</p><small>{{r.ready?'世界已开放':'等待房主进入世界'}} · {{r.connections}} 个连接 · {{r.scope==='lan'?'局域网':'互联网直连'}}</small></div><button class="soft-button" :disabled="!r.ready" @click="copy(r)">复制邀请</button></article></section><section v-if="access.admin" class="card form-stack"><h2>开房授权</h2><form class="form-stack" @submit.prevent="grant(uid)"><label>用户 UID<input v-model="uid" required maxlength="100"></label><button class="primary" :disabled="busy||!uid.trim()">授予创建权限</button></form><div v-for="g in grants" :key="g.uid" class="lobby-room"><span>{{g.name||g.uid}}</span><button class="text-button danger-text" :disabled="busy" @click="grant(g.uid,true)">撤销授权</button></div></section></section></template>
