<script setup>
import {ref,computed,watch,nextTick,onBeforeUnmount,useAttrs} from 'vue';
import {api,state,avatar} from './native.js';
defineOptions({inheritAttrs:false});
const props=defineProps({modelValue:{type:String,default:''},admin:Boolean});
const emit=defineEmits(['update:modelValue']),attrs=useAttrs(),input=ref(),menu=ref(),focused=ref(false),cursor=ref(0),dismissed=ref(''),items=ref([]),error=ref(''),loading=ref(false),index=ref(0),bounds=ref({});
const match=computed(()=>props.modelValue.slice(0,cursor.value).match(/(?:^|\s)@([^\s@]{0,40})$/u)),signature=computed(()=>props.modelValue+'|'+cursor.value),open=computed(()=>focused.value&&state.connected&&!!match.value&&dismissed.value!==signature.value);
function align(){const r=input.value?.getBoundingClientRect();if(!r)return;const view=window.visualViewport,top=view?.offsetTop||0,bottom=top+(view?.height||innerHeight),height=Math.min(224,menu.value?.offsetHeight||224),width=Math.min(340,innerWidth-24);bounds.value={left:Math.max(12,Math.min(r.left,innerWidth-width-12))+'px',top:Math.max(top+8,r.top-height-8>=top?r.top-height-8:Math.min(bottom-height-8,r.bottom+8))+'px',width:width+'px',maxHeight:Math.max(72,Math.min(224,(view?.height||innerHeight)-24))+'px'};}
watch([open,()=>match.value?.[1]],([show,q],_,cleanup)=>{if(!show)return;let valid=true;items.value=[];error.value='';index.value=0;loading.value=true;const timer=setTimeout(async()=>{try{const r=await api('/api/members/search?q='+encodeURIComponent(q||''));if(valid)items.value=[...(props.admin&&(!q||'全体'.includes(q))?[{uid:'all',name:'全体'}]:[]),...r.items];}catch(e){if(valid)error.value=e.message;}finally{if(valid){loading.value=false;await nextTick();align();}}},120);nextTick(align);window.addEventListener('resize',align);window.addEventListener('scroll',align,true);visualViewport?.addEventListener('resize',align);cleanup(()=>{valid=false;clearTimeout(timer);window.removeEventListener('resize',align);window.removeEventListener('scroll',align,true);visualViewport?.removeEventListener('resize',align);});});
function changed(e){cursor.value=e.target.selectionStart;dismissed.value='';emit('update:modelValue',e.target.value);}
async function pick(item){const start=cursor.value-match.value[1].length-1,value=props.modelValue.slice(0,start)+'@'+item.name+' '+props.modelValue.slice(cursor.value),end=start+item.name.length+2;if(attrs.maxlength&&value.length>Number(attrs.maxlength))return;emit('update:modelValue',value);dismissed.value=value+'|'+end;await nextTick();input.value?.focus({preventScroll:true});input.value?.setSelectionRange(end,end);cursor.value=end;}
function key(e){handleKey(e);if(!e.defaultPrevented)attrs.onKeydown?.(e);}
function handleKey(e){if(!open.value||e.isComposing)return;if(e.key==='Escape'){dismissed.value=signature.value;e.preventDefault();}else if(items.value.length&&['ArrowUp','ArrowDown','Enter','Tab'].includes(e.key)){e.preventDefault();if(e.key==='ArrowUp')index.value=(index.value+items.value.length-1)%items.value.length;else if(e.key==='ArrowDown')index.value=(index.value+1)%items.value.length;else void pick(items.value[index.value]);}}
defineExpose({focus:options=>input.value?.focus(options),scrollIntoView:options=>input.value?.scrollIntoView(options)});
</script>
<template><textarea v-bind="{...attrs,onKeydown:undefined}" ref="input" :value="modelValue" aria-autocomplete="list" :aria-expanded="open" @input="changed" @focus="focused=true;cursor=$event.target.selectionStart" @blur="focused=false" @select="cursor=$event.target.selectionStart" @keyup="cursor=$event.target.selectionStart" @keydown="key"/><Teleport to="body"><div v-if="open" ref="menu" class="mobile-mention-menu" :style="bounds" role="listbox" aria-label="提及成员"><p v-if="loading">正在查找成员…</p><p v-else-if="error">{{error}}</p><p v-else-if="!items.length">未找到成员</p><button v-for="(item,i) in items" :key="item.uid" type="button" role="option" :aria-selected="index===i" @pointerdown.prevent @click="pick(item)"><span class="avatar small"><img v-if="avatar(item.uid,item.avatarVersion)" :src="avatar(item.uid,item.avatarVersion)" alt=""><span v-else>{{item.name.slice(0,1)}}</span></span><strong>{{item.name}}</strong><small v-if="item.uid==='all'">通知所有成员</small></button></div></Teleport></template>
<style>
.mobile-mention-menu{position:fixed;z-index:2200;overflow:auto;padding:6px;background:var(--surface,#fff);color:var(--text,#253349);border:1px solid var(--line,#dfe4ed);border-radius:14px;box-shadow:0 12px 32px #10204424;overscroll-behavior:contain}.mobile-mention-menu button{display:flex;align-items:center;gap:10px;width:100%;min-height:46px;padding:8px;border-radius:9px;border:0;background:none;text-align:left;color:inherit}.mobile-mention-menu button[aria-selected=true]{background:var(--soft,#eef2fc)}.mobile-mention-menu small{margin-left:auto;color:var(--muted,#69788e)}.mobile-mention-menu p{padding:8px 12px;font-size:.9rem}
</style>
