<script setup>
import {ref,computed,watch,onMounted,onBeforeUnmount} from 'vue';
import {native,state,rooms,on} from './native.js';
import Icon from './Icon.vue';
import AppSelect from './AppSelect.vue';import AppOverlay from './AppOverlay.vue';import {lyricLines} from '../../../packages/engine/core/lyrics.mjs';
const props=defineProps({visible:Boolean,settings:Object});
const items=ref([]),results=ref([]),query=ref(''),link=ref(''),notice=ref(''),busy=ref(false),active=ref(''),playing=ref(false),loading=ref(false),position=ref(0),duration=ref(0),volume=ref(.5),room=ref('lobby'),sharing=ref(false),mode=ref('list');
const lyrics=ref([]),lyricError=ref(''),candidates=ref([]),lyricBusy=ref(false),floating=ref(false),consent=ref(false),account=ref({allowed:false,loggedIn:false}),accountError=ref(''),privateAudio=ref(false),lyricList=ref();let lyricRun=0;
const lyricIndex=computed(()=>lyrics.value.findLastIndex(line=>line.time<=position.value)),line=computed(()=>lyrics.value[Math.max(0,lyricIndex.value)]);
async function accountStatus(){try{account.value=await native('music',{action:'account.status'});accountError.value='';}catch(e){accountError.value=e.message;account.value={allowed:false,loggedIn:false};}}
async function login(){await action(async()=>{await native('music',{action:'account.login',accepted:true});consent.value=false;await accountStatus();});}
async function logout(){if(privateAudio.value)pause();await action(async()=>{await native('music',{action:'account.logout'});await accountStatus();});}
async function loadLyrics(netId){const run=++lyricRun;lyrics.value=[];candidates.value=[];lyricError.value='';if(!current.value)return;lyricBusy.value=true;try{const id=netId||current.value.lyricsNetId||current.value.netId;if(!id){const r=await native('music',{action:'search',query:current.value.title+' '+current.value.artist});if(run===lyricRun)candidates.value=r.items.slice(0,8);}else{const r=await native('music',{action:'lyrics',id});if(run===lyricRun)lyrics.value=lyricLines(r.original,r.translation);}}catch(e){if(run===lyricRun)lyricError.value=e.message;}finally{if(run===lyricRun)lyricBusy.value=false;}}
async function bindLyrics(t){if(!current.value)return;current.value.lyricsNetId=t.netId;persist();await loadLyrics(t.netId);}
watch(active,()=>loadLyrics());watch(lyricIndex,()=>{const box=lyricList.value,node=box?.querySelector('[aria-current=true]');if(box&&node)box.scrollTo({top:node.offsetTop-box.offsetTop-box.clientHeight/2+node.clientHeight/2,behavior:props.settings.animations&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'smooth':'instant'});});
const removeAccessListener=on('music-access-changed',()=>{if(privateAudio.value)pause();void accountStatus();});watch(()=>state.user.uid,()=>{if(privateAudio.value)pause();void accountStatus();});
const current=computed(()=>items.value.find(x=>x.id===active.value));
const audio=new Audio();audio.preload='metadata';audio.crossOrigin='anonymous';let generation=0,attempted=new Set(),timer,context,source,gain,worklet;
function persist(){localStorage.setItem('hxz-music-library',JSON.stringify(items.value));}
function add(track){if(!items.value.some(x=>x.id===track.id)&&items.value.length<500){items.value.push(track);persist();}return track;}
async function action(fn){if(busy.value)return;busy.value=true;notice.value='';try{await fn();}catch(e){if(e.message!=='已取消')notice.value=e.message;}finally{busy.value=false;}}
async function search(){await action(async()=>{results.value=(await native('music',{action:'search',query:query.value})).items;});}
async function importList(){await action(async()=>{const r=await native('music',{action:'playlist',link:link.value});let added=0;for(const t of r.items){if(items.value.length>=500)break;if(!items.value.some(x=>x.id===t.id)){add(t);added++;}}notice.value=`${r.name} · 已导入 ${added} 首，音乐库共 ${items.value.length} 首`;link.value='';});}
async function importLocal(){await action(async()=>{const r=await native('pick',{kind:'music'});add({id:r.url,title:r.name||'本地音乐',artist:'本地文件',url:r.url,source:'local'});});}
function clock(s){return Math.floor((s||0)/60)+':'+String(Math.floor((s||0)%60)).padStart(2,'0');}
function nextId(step=1){const start=items.value.findIndex(t=>t.id===active.value),n=items.value.length;if(!n)return '';for(let i=1;i<=n;i++){const t=items.value[(start+step*i+n*2)%n];if(!attempted.has(t.id))return t.id;}return '';}
async function play(id,chain=false){
 const t=items.value.find(t=>t.id===id);if(!t)return;if(!chain)attempted=new Set();const token=++generation;audio.pause();clearTimeout(timer);loading.value=true;playing.value=false;active.value=id;attempted.add(id);
 try{const prepared=t.url?{url:t.url}:await native('music',{action:'prepare',id:t.netId});if(token!==generation)return;privateAudio.value=!!prepared.privateAudio;audio.src=prepared.url;audio.volume=volume.value;timer=setTimeout(()=>{if(token===generation)failed('读取音频超时');},25000);await audio.play();if(token!==generation)return;playing.value=true;}catch(e){if(token===generation)failed(e.message);}
}
function failed(reason){clearTimeout(timer);loading.value=false;playing.value=false;notice.value=(current.value?.title||'此曲目')+' 无法播放，正在尝试下一首';const next=nextId();if(next)void play(next,true);else{audio.pause();generation++;notice.value='本轮曲目均无法播放，已停止。'+String(reason||'请检查文件或网络').slice(0,130);}}
function pause(){generation++;audio.pause();clearTimeout(timer);loading.value=false;playing.value=false;}
async function toggle(){if(playing.value||loading.value){pause();return;}if(audio.src&&active.value){try{if(privateAudio.value){await accountStatus();if(!account.value.allowed||!account.value.loggedIn)throw Error('网易云账号授权已失效');}await context?.resume();await audio.play();playing.value=true;}catch(e){failed(e.message);}}else if(items.value[0])void play(items.value[0].id);}
function skip(step){attempted=new Set();const id=nextId(step);if(id)void play(id);}
async function remove(t){if(active.value===t.id){pause();active.value='';audio.removeAttribute('src');audio.load();}items.value=items.value.filter(x=>x.id!==t.id);persist();if(t.source==='local')await native('music',{action:'remove',url:t.url}).catch(()=>{});}
audio.addEventListener('playing',()=>{clearTimeout(timer);loading.value=false;playing.value=true;if(notice.value.includes('正在尝试下一首'))notice.value='已跳过不可播放的曲目，继续播放 '+(current.value?.title||'下一首');});
audio.addEventListener('timeupdate',()=>position.value=audio.currentTime);
audio.addEventListener('durationchange',()=>duration.value=Number.isFinite(audio.duration)?audio.duration:0);
audio.addEventListener('error',()=>{if(active.value&&(playing.value||loading.value))failed('音频格式或链接不可用');});
audio.addEventListener('ended',()=>{attempted=new Set();void play(mode.value==='one'?active.value:nextId());});
watch(volume,value=>{audio.volume=Number(value);});
async function listen(){await action(async()=>{await native('voiceSettings',{muted:true,deafened:false});await native('voiceJoin',{room:room.value});notice.value='加入后可收听同房间伙伴分享的音乐，麦克风保持关闭';});}
async function stopShare(){sharing.value=false;worklet?.port.postMessage(false);await native('musicShare',{enabled:false}).catch(()=>{});}
async function share(){if(sharing.value){await stopShare();return;}await action(async()=>{if(!state.room)throw Error('请先加入一个语音房间');
 if(!context){context=new AudioContext({sampleRate:48000});await context.audioWorklet.addModule(new URL('./music-capture.js',import.meta.url));source=context.createMediaElementSource(audio);gain=context.createGain();gain.gain.value=1;source.connect(gain).connect(context.destination);worklet=new AudioWorkletNode(context,'hxz-music-capture');source.connect(worklet).connect(context.destination);worklet.port.onmessage=e=>{if(!sharing.value)return;const bytes=new Uint8Array(e.data);let raw='';for(const b of bytes)raw+=String.fromCharCode(b);window.HXZNative?.musicPCM?.(btoa(raw));};}
 await context.resume();await native('musicShare',{enabled:true});sharing.value=true;worklet.port.postMessage(true);notice.value='正在分享播放器声音，麦克风状态保持不变';});}
watch(()=>state.room,()=>{if(sharing.value)void stopShare();});
function hidden(){if(document.hidden){pause();void stopShare();}else void accountStatus();}
onMounted(()=>{void accountStatus();try{items.value=JSON.parse(localStorage.getItem('hxz-music-library')||'[]').filter(x=>x&&typeof x.id==='string').slice(0,500);}catch{}if(props.settings.music){add({id:props.settings.music,title:'原背景音乐',artist:'本地文件',url:props.settings.music,source:'local'});props.settings.music='';}document.addEventListener('visibilitychange',hidden);});
onBeforeUnmount(()=>{removeAccessListener();lyricRun++;pause();void stopShare();context?.close();audio.removeAttribute('src');audio.load();document.removeEventListener('visibilitychange',hidden);});
</script>
<template>
<section v-show="visible" class="content-page music-page">
 <div class="page-toolbar"><h1>音乐播放器</h1><span class="tag">{{items.length}} / 500</span></div>
 <p v-if="notice" class="card music-notice" role="status">{{notice}}</p>
 <section class="card music-now"><div class="music-track-icon"><Icon name="music"/></div><div><small>正在播放</small><h2>{{current?.title||'选一首喜欢的音乐'}}</h2><p class="muted">{{current?.artist||'本地音乐 · 网易云可用外链'}}</p></div><div class="music-progress"><input type="range" min="0" :max="duration||1" :value="position" step=".1" aria-label="播放进度" @change="audio.currentTime=Number($event.target.value)"><div><small>{{clock(position)}}</small><small>{{clock(duration)}}</small></div></div><div class="music-buttons"><button class="soft-button" aria-label="上一首" @click="skip(-1)"><Icon name="previous"/></button><button class="primary" :disabled="!items.length" @click="toggle"><Icon :name="playing||loading?'pause':'play'"/>{{loading?'取消加载':playing?'暂停':'播放'}}</button><button class="soft-button" aria-label="下一首" @click="skip(1)"><Icon name="next"/></button></div><label class="music-volume">音量<input v-model.number="volume" type="range" min="0" max="1" step=".05" aria-label="音乐音量"></label><AppSelect v-model="mode" label="播放方式" :options="[{value:'list',label:'列表循环'},{value:'one',label:'单曲循环'}]"/></section>
 <section class="card form-stack"><h2>网易云音乐</h2><div class="mobile-music-account"><div><strong>{{account.loggedIn?'个人网易云账号已登录':'使用自己的网易云账号'}}</strong><small>{{accountError||(account.allowed?'登录状态仅保存在此设备':'此功能需要社区管理员授权')}}</small></div><button v-if="account.loggedIn" class="soft-button" @click="logout">退出</button><button v-else class="soft-button" :disabled="!account.allowed" @click="consent=true">登录</button><button class="icon-button" aria-label="刷新网易云登录状态" @click="accountStatus"><Icon name="refresh"/></button></div><form class="music-search" @submit.prevent="search"><input v-model="query" placeholder="搜索歌曲、歌手" maxlength="200" aria-label="搜索歌曲"><button class="soft-button" :disabled="busy||!query.trim()">搜索</button></form><form class="music-search" @submit.prevent="importList"><input v-model="link" placeholder="公开歌单链接或 ID" aria-label="网易云歌单链接"><button class="soft-button" :disabled="busy||!link.trim()">导入歌单</button></form><p class="muted">未登录时使用可用外链；登录后按你的账号权限播放。受限曲目会自动跳过。</p><div v-if="results.length" class="music-list search-results"><button v-for="t in results" :key="t.id" class="music-song" @click="add(t);play(t.id)"><Icon name="plus"/><span><strong>{{t.title}}</strong><small>{{t.artist}}</small></span></button></div></section>
 <section class="card form-stack"><h2>一起听</h2><AppSelect v-model="room" label="选择房间" :options="rooms.map(r=>({value:r.id,label:r.name}))"/><div class="actions"><button class="soft-button" :disabled="busy||!state.connected" @click="listen"><Icon name="headphones"/>加入收听</button><button class="soft-button" :disabled="!state.room||busy" :aria-pressed="sharing" @click="share">{{sharing?'停止分享':'分享播放器'}}</button></div><p class="muted">{{state.room?'当前频道：'+(rooms.find(r=>r.id===state.room)?.name||state.room):'同一语音房间内收听，默认不开麦'}}。切换页面继续播放，进入后台暂停音乐分享。</p></section>
 <section class="card music-library"><header><h2>我的音乐</h2><button class="soft-button" :disabled="busy||items.length>=500" @click="importLocal"><Icon name="plus"/>导入音乐</button></header><p v-if="!items.length" class="empty-note">导入普通音频、常见 NCM 或旧 QMC，或搜索网易云音乐。单曲最多 50 MB。</p><div class="music-list"><div v-for="t in items" :key="t.id" class="music-song" :class="{selected:t.id===active}"><button class="song-play" @click="play(t.id)"><Icon :name="active===t.id&&playing?'music':'play'"/><span><strong>{{t.title}}</strong><small>{{t.artist}}</small></span></button><button class="icon-button" :aria-label="'移除 '+t.title" @click="remove(t)"><Icon name="close"/></button></div></div></section>
<section class="card form-stack"><div class="mobile-card-heading"><h2>歌曲歌词</h2><button class="text-button" :disabled="!current" @click="floating=!floating">{{floating?'收回歌词':'其他页面也显示'}}</button><button class="icon-button" aria-label="刷新歌词" :disabled="lyricBusy||!current" @click="loadLyrics()"><Icon name="refresh"/></button></div><div ref="lyricList" class="mobile-lyrics-list"><button v-for="(row,i) in lyrics" :key="i" :aria-current="i===lyricIndex" @click="audio.currentTime=row.time"><span>{{row.text}}</span><small v-if="row.translation">{{row.translation}}</small></button><p v-if="!lyrics.length" class="empty-note">{{lyricBusy?'正在获取歌词…':lyricError||'暂无同步歌词'}}</p></div><template v-if="candidates.length"><p class="muted">为本地音乐选择对应歌词</p><button v-for="candidate in candidates" :key="candidate.id" class="soft-button" @click="bindLyrics(candidate)">{{candidate.title}} · {{candidate.artist}}</button></template></section>
</section>
<Teleport to="#mobile-music-dock" defer><aside v-if="!visible&&current" class="mobile-music-dock" :class="{expanded:floating}"><button class="icon-button" :aria-label="playing?'暂停音乐':'播放音乐'" @click="toggle"><Icon :name="playing?'pause':'play'"/></button><div><small>{{current.title}}</small><strong v-if="floating">{{line?.text||(lyricBusy?'正在获取歌词…':lyricError||'暂无歌词')}}</strong><span v-if="floating&&line?.translation">{{line.translation}}</span></div><button class="icon-button" :aria-label="floating?'收回歌词':'展开歌词'" @click="floating=!floating"><Icon :name="floating?'close':'music'"/></button></aside></Teleport>
<AppOverlay :open="consent" label="登录个人网易云账号" @close="consent=false"><section class="sheet"><header class="sheet-header"><h2>登录个人网易云账号</h2><button class="icon-button" aria-label="关闭登录说明" @click="consent=false"><Icon name="close"/></button></header><div class="sheet-body form-stack"><p>接下来打开网易云官方登录页面。请只登录你自己的账号。</p><p>登录状态只保存在此设备，不会传给社区管理员或其他玩家。在公用设备使用后请退出。</p><p>第三方播放器可能触发验证码、异地登录或账号风控。可播放内容由你的账号、会员和版权权限决定，社区授权不会提供额外的曲目权限。</p><div class="actions"><button class="soft-button" @click="consent=false">取消</button><button class="primary" :disabled="busy" @click="login">同意并打开官方登录</button></div><p v-if="notice" class="error-note">{{notice}}</p></div></section></AppOverlay>
</template>
