const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.9 13A9 9 0 0 1 11 3.1 9 9 0 1 0 20.9 13Z"/></svg>';
export const WEREWOLF={id:'werewolf',number:12,name:'月下圆桌',tag:'狼人杀 · 六人社区联机',description:'用推理寻找同伴，在夜色与天光之间作出选择',social:true,color:'#adb6df'};
export function mountWerewolf(root,request){
 let room=null,lobby=[],busy=false,error='',text='',title='',target='',closed=false,loading=false,turn='',confirmLeave=false,generation=0;
 root.classList.add('werewolf');
 const button=(label,action,more='',disabled=false)=>`<button type="button" data-action="${action}" ${more} ${disabled?'disabled':''}>${label}</button>`;
 const action=(name,payload={})=>mutate('/api/werewolf/'+room.id,{action:name,...payload});
 async function mutate(url,data){if(busy||closed)return;busy=true;generation++;error='';render();try{const result=await request(url,'POST',data);if(closed)return;if(result.left){room=null;try{sessionStorage.removeItem('hxz-werewolf-room');}catch{}}else{room=result;try{sessionStorage.setItem('hxz-werewolf-room',room.id);}catch{}}if(data.action==='chat')text='';target='';confirmLeave=false;}catch(e){error=e.message;}finally{busy=false;if(!closed){render();void refresh();}}}
 async function refresh(){if(closed||loading||busy||document.hidden)return;loading=true;let changed=false;const gen=generation,id=room?.id;try{if(room){const value=await request('/api/werewolf/'+room.id);if(closed||busy||generation!==gen||room?.id!==id)return;changed=JSON.stringify(room)!==JSON.stringify(value);room=value;if(turn!==room.turn){target='';turn=room.turn;}}else{const items=(await request('/api/werewolf')).items||[];if(closed||busy||generation!==gen||room?.id!==id)return;changed=JSON.stringify(lobby)!==JSON.stringify(items);lobby=items;}if(error){changed=true;error='';}}catch(e){if(!closed&&generation===gen){changed=error!==e.message;error=e.message;if(room&&/房间已结束|服务重启|房间不存在/.test(e.message)){room=null;changed=true;confirmLeave=false;}}}finally{loading=false;if(!closed&&changed)render();}}
 function render(){if(closed)return;const openDetails=[...root.querySelectorAll('details[open]')].map(e=>e.className);const active=root.contains(document.activeElement)?document.activeElement:null,focus=active?.dataset.field,pos=active?.selectionStart,scroll=root.querySelector('.wolf-chat-log'),atEnd=!scroll||scroll.scrollHeight-scroll.scrollTop-scroll.clientHeight<45,oldScroll=scroll?.scrollTop||0;
  const r=room,me=r?.me;root.innerHTML=`<header class="wolf-heading"><div class="wolf-title">${icon}<div><small>12 · 社区桌游</small><h2>月下圆桌</h2></div></div>${r?button('离开房间','leave'):button('刷新房间','refresh')}</header>${error?`<p class="wolf-error" role="alert">${safe(error)}</p>`:''}`;
  if(!r){root.innerHTML+=`<div class="wolf-layout"><section class="wolf-card wolf-create"><div class="wolf-illustration">${icon}<span>月升，故事开始</span></div><h3>开一张六人桌</h3><p>2 狼人 · 1 预言家 · 1 女巫 · 2 村民</p><label>房间名称<input data-field="title" value="${safe(title)}" placeholder="给圆桌起个名字" maxlength="40"/></label>${button('创建房间','create','class="primary"',busy)}<small>不足六人可由房主补齐练习机器人。六位真人参与时，胜方计入每周联机积分。</small></section><section class="wolf-card"><h3>社区圆桌 <small>${lobby.length} 个房间</small></h3><div class="wolf-room-list">${lobby.length?lobby.map(v=>`<article><div><strong>${safe(v.title)}</strong><small>${v.count}/6 · ${v.phase==='waiting'?'等待伙伴':v.phase==='finished'?'已结束':'对局中'}</small></div>${button(v.joined?'继续':'加入',v.joined?'return':'join',`data-id="${safe(v.id)}"`,busy||!v.joined&&(v.phase!=='waiting'||v.count>=6))}</article>`).join(''):'<p class="wolf-empty">还没有圆桌，邀请伙伴一起开局。</p>'}</div><details class="wolf-rules"><summary>玩法与胜负</summary><p>夜晚狼人共同选择目标，预言家查验一人，女巫可用一次解药和一次毒药，每夜至多用一瓶。白天自由讨论，再同时投票放逐一人；平票无人出局。狼人全部出局，好人胜；狼人数量达到其余存活玩家数量，狼人胜。12 轮后未分胜负为和局。超时视为跳过。</p></details></section></div>`;
  }else{
   const stage={waiting:'等待入座',night:'夜幕降临',discussion:'自由讨论',vote:'放逐投票',finished:'本局结束'}[r.phase],left=Math.max(0,Math.ceil((r.deadline-Date.now())/1000));
   root.innerHTML+=`<div class="wolf-stage ${r.phase==='night'?'night':''}"><div><small>${safe(r.title)} · ${r.ranked?'真人对局':'练习圆桌'}</small><h3>${stage}${r.phase!=='waiting'?' · 第 '+r.day+' 轮':''}</h3></div><strong>${r.phase==='waiting'?'6 人桌':r.phase==='finished'?'已结算':left+' 秒'}</strong></div><div class="wolf-layout"><section class="wolf-card"><div class="wolf-seats">${Array.from({length:6},(_,i)=>{const p=r.players[i],can=p&&me?.canAct&&me.targets.includes(p.uid);return `<button class="wolf-seat ${p&&!p.alive?'eliminated':''} ${target===p?.uid?'selected':''}" data-action="target" data-id="${safe(p?.uid)}" ${!can||busy?'disabled':''} aria-pressed="${target===p?.uid}"><span class="wolf-seat-number">${i+1}</span><span class="wolf-avatar">${p?safe(p.name.slice(0,1)):'+'}</span><strong>${p?safe(p.name):'等待伙伴'}</strong><small>${!p?'空座':r.phase==='waiting'?(p.ready?'已准备':'未准备'):p.alive?(me?.teammates.includes(p.uid)?'狼人同伴':p.uid===me?.uid?'你在这里':'存活'):'已出局'}${p?.bot?' · 机器人':''}</small>${p?.role?`<em>${safe(p.role)}</em>`:''}</button>`;}).join('')}</div>
   <div class="wolf-private"><small>仅你可见</small><h3>${safe(me?.role)}</h3>${me?.checks?.length?`<p>${me.checks.map(c=>safe(c.name)+'：'+(c.wolf?'狼人':'好人')).join(' · ')}</p>`:''}${!me?.alive&&r.phase!=='finished'?'<p>你已出局，可以继续观看；暂时不能发言。</p>':''}
   ${r.phase==='waiting'?`<div class="wolf-actions">${button(r.players.find(p=>p.uid===me?.uid)?.ready?'取消准备':'准备','ready','',busy)}${me?.uid===r.host?button(r.players.length<6?'补齐机器人并开始':'开始游戏','start','class="primary"',busy):''}</div>`:me?.canAct?`<p>${me.action==='wolves'?'与狼人同伴选择同一位目标；平票无人遇袭。':me.action==='seer'?'选择一位玩家，查验他的阵营。':me.action==='witch'?'今夜遇袭：'+safe(r.players.find(p=>p.uid===me.victim)?.name||'无人')+'。解药与毒药每局各一次。':'点击上方玩家，然后确认投票。'}</p><div class="wolf-actions">${me.action==='witch'?`${button('使用解药','heal','',busy||!me.heal||!me.victim)}${button('对所选玩家用毒','poison','',busy||!me.poison||!target)}`:button(me.action==='vote'?'确认投票':'确认选择','act','class="primary"',busy||!target)}${button(me.action==='vote'?'弃票':'跳过','skip','',busy)}</div>`:`<p>${r.phase==='finished'?r.result==='village'?'好人阵营获胜':r.result==='wolves'?'狼人阵营获胜':'本局和局':me?.submitted?'已提交，等待其他玩家。':r.phase==='discussion'?'说说你的判断，留意伙伴的发言。':'等待当前回合结束。'}</p>`}</div>
   <details class="wolf-records"><summary>圆桌记录</summary>${r.log.map(v=>`<p>${safe(v.text)}</p>`).join('')}</details></section>
   <section class="wolf-card wolf-chat"><h3>圆桌讨论 <small>${r.canChat?'可以发言':'等待白天'}</small></h3><div class="wolf-chat-log" aria-live="polite">${r.chat.length?r.chat.map(v=>`<article><header><strong>${safe(v.name)}</strong><time>${new Date(v.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time></header><p>${safe(v.text)}</p></article>`).join(''):'<p class="wolf-empty">白天一起讨论线索，夜晚请保持安静。</p>'}</div><form class="wolf-compose"><input data-field="text" aria-label="圆桌消息" maxlength="300" value="${safe(text)}" placeholder="分享你的判断…" ${!r.canChat?'disabled':''}/><button type="submit" ${busy||!r.canChat?'disabled':''}>发送</button></form><small>夜间行动只对本人可见。请勿在公开聊天中发送截图泄露身份。</small></section></div>`;
   if(confirmLeave)root.innerHTML+=`<div class="wolf-leave-confirm" role="alert"><p>${['waiting','finished'].includes(r.phase)?'离开当前圆桌？':'离开后将退出本局并出局，确定离开？'}</p>${button('留在圆桌','stay')}${button('确认离开','confirm-leave')}</div>`;
  }
  for(const name of openDetails)root.querySelector('details.'+name)?.setAttribute('open','');
  const field=focus?root.querySelector(`[data-field="${focus}"]`):null;if(field){field.focus({preventScroll:true});try{field.setSelectionRange(pos,pos);}catch{}}
  const newScroll=root.querySelector('.wolf-chat-log');if(newScroll)newScroll.scrollTop=atEnd?newScroll.scrollHeight:oldScroll;
 }
 const click=e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;switch(b.dataset.action){
  case 'create':void mutate('/api/werewolf',{title});break;case 'join':void mutate('/api/werewolf/'+b.dataset.id,{action:'join'});break;
  case 'return':void mutate('/api/werewolf/'+b.dataset.id,{action:'join'});break;case 'refresh':void refresh();break;
  case 'target':target=b.dataset.id;render();break;case 'ready':void action('ready');break;case 'start':void action('start',{fillBots:true});break;
  case 'leave':confirmLeave=true;render();break;case 'stay':confirmLeave=false;render();break;case 'confirm-leave':void action('leave');break;
  case 'act':void action('act',{turn:room.turn,target});break;case 'heal':case 'poison':case 'skip':void action('act',{turn:room.turn,choice:b.dataset.action,target:b.dataset.action==='poison'?target:null});break;
 }};
 const input=e=>{if(e.target.dataset.field==='text')text=e.target.value;if(e.target.dataset.field==='title')title=e.target.value;};
 const submit=e=>{e.preventDefault();if(text.trim()&&room?.canChat)void action('chat',{text});};
 root.addEventListener('click',click);root.addEventListener('input',input);root.addEventListener('submit',submit);
 // The active room can be resumed from the lobby; stale IDs do not block it.
 render();void refresh();const timer=setInterval(()=>{const counter=root.querySelector('.wolf-stage>strong');if(counter&&room&&!['waiting','finished'].includes(room.phase))counter.textContent=Math.max(0,Math.ceil((room.deadline-Date.now())/1000))+' 秒';void refresh();},2000);
 return ()=>{closed=true;clearInterval(timer);root.removeEventListener('click',click);root.removeEventListener('input',input);root.removeEventListener('submit',submit);root.replaceChildren();};
}
