import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {once} from 'node:events';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_PATH?pathToFileURL(process.env.PLAYWRIGHT_PATH).href:'playwright');
const root=fileURLToPath(new URL('../',import.meta.url));
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const name=url.pathname==='/'?'index.html':url.pathname.slice(1);const bytes=await fs.readFile(path.join(process.env.WEB_DIST||path.join(root,'web/dist'),name));res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(bytes);}catch{res.writeHead(404);res.end();}});
server.listen(0,'127.0.0.1');await once(server,'listening');
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:390,height:844}}),calls=[],errors=[];page.setDefaultTimeout(10000);
page.on('pageerror',e=>errors.push(e.message));
const users=[{id:'self',uid:'demo',name:'小云',room:null},{id:'other',uid:'demo2',name:'旅人',room:'lobby'}];
const state={connected:true,connection:'已连接',hasAccount:true,server:'https://qqbot.hxzmc.top',profiles:[],user:{uid:'demo',name:'小云'},room:'',recoveringRoom:'',users,messages:Array.from({length:10},(_,i)=>({id:i,uid:i%2?'demo':'demo2',name:i%2?'小云':'旅人',body:i%2?'可以，待会儿语音里聊。':'今天一起去看看新机器吗？',created:Date.now()-(10-i)*180000})),muted:false,deafened:false,ptt:false};
await page.exposeBinding('nativeCall',async(_,raw)=>{const {id,op,input}=JSON.parse(raw);calls.push({op,input});let data=true;if(op==='state')data=state;if(op==='appUpdate')data={currentVersion:'0.4.2',currentBuild:40204,autoCheck:true,autoDownload:true,phase:'idle'};if(op==='api')data={admin:false,reviewer:false,items:[],total:0,minecraft:['1.21.1'],create:['6.0']};if(op==='voiceJoin'){state.room=input.room;state.users[0].room=input.room;await page.evaluate(s=>window.HXZEvent('state',s),state);}if(op==='voiceLeave'){state.room='';state.users[0].room=null;await page.evaluate(s=>window.HXZEvent('state',s),state);}if(op==='voiceSettings'){Object.assign(state,input);await page.evaluate(s=>window.HXZEvent('state',s),state);}await page.evaluate(r=>window.HXZEvent('result',r),{id,data,error:null});});
await page.addInitScript(()=>{localStorage.setItem('hxz-mobile-settings',JSON.stringify({theme:'light',font:16}));window.HXZNative={call:raw=>window.nativeCall(raw)};});

try{
 await page.goto('http://127.0.0.1:'+server.address().port);
 await page.getByRole('navigation').getByRole('button',{name:'我的',exact:true}).click();
 assert.equal(await page.locator('select').count(),0);
 await page.getByRole('button',{name:'主题',exact:true}).click();
 await page.getByRole('dialog',{name:'主题',exact:true}).waitFor();
 assert.equal(await page.getByRole('dialog').locator('.settings-row .avatar').count(),3,'主题选项必须复用角色切换行');
 await page.getByRole('option',{name:'深色',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.getByRole('button',{name:'说话方式',exact:true}).click();
 await page.getByRole('option',{name:'按住说话',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 assert.equal(calls.filter(c=>c.op==='voiceSettings').at(-1).input.ptt,true);
 await page.getByRole('button',{name:'退出登录',exact:true}).click();
 await page.getByRole('alertdialog').waitFor();
 await page.evaluate(()=>window.HXZEvent('back',{}));
 await page.getByRole('alertdialog').waitFor({state:'detached'});
 assert.equal(calls.filter(c=>c.op==='logout').length,0);
 await page.getByRole('button',{name:'界面动效',exact:true}).click();
 await page.getByRole('option',{name:'关闭',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 assert.equal(await page.locator('html').getAttribute('data-motion'),'off');
 assert.equal(await page.getByRole('button',{name:'主题',exact:true}).evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
 await page.getByRole('button',{name:'界面动效',exact:true}).click();
 await page.getByRole('option',{name:'开启',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 await page.getByRole('navigation').getByRole('button',{name:'蓝图',exact:true}).click();
 await page.getByRole('button',{name:'筛选',exact:true}).click();
 await page.getByRole('button',{name:'Minecraft 版本',exact:true}).click();
 assert.equal(await page.locator('.sheet-backdrop').count(),2);
 await page.evaluate(()=>window.HXZEvent('back',{}));
 await page.getByRole('dialog',{name:'Minecraft 版本',exact:true}).waitFor({state:'detached'});
 assert.equal(await page.getByRole('dialog',{name:'社区面板',exact:true}).count(),1);
 await page.evaluate(()=>window.HXZEvent('back',{}));
 await page.getByRole('dialog').waitFor({state:'detached'});
 await page.getByRole('navigation').getByRole('button',{name:'我的',exact:true}).click();
 await page.getByRole('button',{name:'主题',exact:true}).click();
 for(const width of [320,390,820]){
  await page.setViewportSize({width,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 }
 await page.setViewportSize({width:390,height:844});
 await page.waitForFunction(()=>!document.querySelector('.overlay-enter-active'));await page.screenshot({path:path.join(root,'.test','unified-picker.png')});
 await page.getByRole('option',{name:'浅色',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.getByRole('button',{name:'主题',exact:true}).evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.getByRole('button',{name:'检查更新',exact:true}).click();
 assert(calls.some(c=>c.op==='appUpdate'&&c.input.action==='check'));
 const ready={currentVersion:'0.4.2',currentBuild:40204,autoCheck:true,autoDownload:true,phase:'downloading',message:'正在下载更新…',received:1024,total:2048,source:'GH-Proxy 镜像',version:{versionCode:40205,versionName:'0.4.2',notes:'界面修复'}};
 await page.evaluate(s=>window.HXZEvent('appUpdate',s),ready);
 assert.equal(await page.locator('progress').getAttribute('value'),'1024');
 await page.getByText('50%',{exact:true}).waitFor();
 await page.evaluate(s=>window.HXZEvent('appUpdate',{...s,phase:'ready',message:'更新已就绪，点击安装'}),ready);
 await page.getByRole('button',{name:'安装更新',exact:true}).click();
 assert(calls.some(c=>c.op==='appUpdate'&&c.input.action==='install'));
 await page.getByRole('checkbox',{name:/自动检查更新/}).uncheck();
 assert(calls.some(c=>c.op==='appUpdate'&&c.input.action==='settings'&&c.input.autoCheck===false));
 await page.getByRole('navigation').getByRole('button',{name:'语音',exact:true}).click();
 assert.equal(await page.locator('.workspace').evaluate(e=>e.getAnimations().length>0),true);
 await page.getByRole('button',{name:/旅人休息室/}).click();
 assert.equal(await page.locator('.voice-room.selected>.icon').evaluate(e=>getComputedStyle(e).animationName),'voice-breathe');
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({pass:true,checks:'shared role-style options, boolean settings, overlay back, motion on/off, responsive widths, update progress/install/settings callbacks, visible navigation and voice motion'}));
}finally{await browser.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
