<script setup>
import {ref,watch,onMounted,onBeforeUnmount,nextTick} from 'vue';
import {native,state} from './native.js';
import AppSelect from './AppSelect.vue';
const props=defineProps({settings:Object,controls:Boolean});const video=ref(),canvas=ref(),music=ref(),error=ref(''),showControls=ref(false);let frame=0,last=0;
watch(()=>props.controls,async value=>{showControls.value=false;if(value){await nextTick();showControls.value=true;}},{immediate:true});
function paint(now){const v=video.value,c=canvas.value,q=props.settings.videoQuality||'efficient';if(v&&c&&!v.paused&&q!=='original'&&now-last>=(q==='balanced'?1000/30:1000/15)){last=now;const scale=Math.min(1,(q==='balanced'?1920:1280)/innerWidth,(q==='balanced'?1080:720)/innerHeight);const w=Math.round(innerWidth*scale),h=Math.round(innerHeight*scale);if(c.width!==w||c.height!==h){c.width=w;c.height=h;}if(v.videoWidth){const ratio=Math.max(w/v.videoWidth,h/v.videoHeight);c.getContext('2d',{alpha:false}).drawImage(v,(w-v.videoWidth*ratio)/2,(h-v.videoHeight*ratio)/2,v.videoWidth*ratio,v.videoHeight*ratio);}}if(v&&!v.paused)frame=requestAnimationFrame(paint);}
function playing(){cancelAnimationFrame(frame);frame=requestAnimationFrame(paint);}
async function pick(kind){try{const value=await native('pick',{kind});props.settings[kind==='music'?'music':'background']=value.url;}catch(e){if(e.message!=='已取消')error.value=e.message;}}
async function sync(){await nextTick();if(video.value){if(document.hidden)video.value.pause();else void video.value.play().catch(()=>{});}if(music.value){music.value.volume=props.settings.musicVolume??.3;if(document.hidden||state.room)music.value.pause();else void music.value.play().catch(()=>{});}}
function refresh(){music.value?.load();void sync();}
watch(()=>[props.settings.background,props.settings.music,props.settings.musicVolume,state.room],sync);
onMounted(()=>{document.addEventListener('visibilitychange',sync);void sync();});onBeforeUnmount(()=>{cancelAnimationFrame(frame);document.removeEventListener('visibilitychange',sync);});
</script>
<template><Teleport v-if="showControls" to="#media-controls"><div class="card form-stack"><label>动画速度<AppSelect v-model="settings.animationSpeed" label="动画速度" :options="[{value:0,label:'关闭'},{value:.5,label:'舒缓'},{value:1,label:'标准'},{value:1.5,label:'轻快'},{value:2,label:'快速'}]"/></label><label>面板不透明度 · {{Math.round((settings.surfaceOpacity??1)*100)}}%<input v-model.number="settings.surfaceOpacity" type="range" min=".15" max="1" step=".05"/></label><div class="media-actions"><button @click="pick('background')">背景图片 / 视频</button><button @click="settings.background=''">清除背景</button><button @click="pick('music')">背景音乐</button><button @click="settings.music=''">关闭音乐</button><button @click="refresh">刷新播放</button></div><label>视频绘制质量<AppSelect v-model="settings.videoQuality" label="视频绘制质量" :options="[{value:'original',label:'原始画质'},{value:'balanced',label:'均衡 · 最高 1080p / 30 帧'},{value:'efficient',label:'节能 · 最高 720p / 15 帧'}]"/></label><label>音乐音量<input v-model.number="settings.musicVolume" type="range" min="0" max="1" step=".05"/></label><p class="muted">视频、音乐限 50 MB。应用转入后台暂停播放，加入语音时暂停音乐。</p><p v-if="error" role="alert">{{error}}</p></div></Teleport><Teleport to="body"><div v-if="settings.background" class="mobile-backdrop"><video v-if="/\.(mp4|webm)$/.test(settings.background)" ref="video" :src="settings.background" muted autoplay loop playsinline @play="playing" :class="{source:settings.videoQuality!=='original'}"/><canvas v-if="/\.(mp4|webm)$/.test(settings.background)" v-show="settings.videoQuality!=='original'" ref="canvas"/><img v-else :src="settings.background" alt=""/></div><audio v-if="settings.music" ref="music" :src="settings.music" loop/></Teleport></template>
<style scoped>.media-actions{display:flex;gap:8px;flex-wrap:wrap}.media-actions button{border:1px solid var(--line);background:var(--soft);color:var(--text);border-radius:10px;padding:10px;font:inherit}.mobile-backdrop{position:fixed;inset:0;z-index:-1;pointer-events:none;overflow:hidden}.mobile-backdrop>*{width:100%;height:100%;object-fit:cover;position:absolute;inset:0}.mobile-backdrop .source{width:1px;height:1px;opacity:0}</style>
