import http from 'node:http';import path from 'node:path';import {readFile,stat} from 'node:fs/promises';import {createReadStream} from 'node:fs';import {pipeline} from 'node:stream/promises';import {initializeCMS,handleCMS,readContent,uploadsDirectory} from './cms.mjs';import {handleAPI} from './api.mjs';import {render} from './render.mjs';
const root=path.resolve(import.meta.dirname,'../dist'),port=Number(process.env.PORT||4332),host=process.env.HOST||'127.0.0.1';
await initializeCMS();const template=await readFile(path.join(root,'index.html'),'utf8');const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon','.woff2':'font/woff2'};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');if(url.pathname.startsWith('/api/admin/'))return await handleCMS(req,res);if(url.pathname==='/health'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true,product:'HXZ NEXT Website',version:'0.5.2-air'}));}const request=new Request('http://localhost'+req.url,{headers:req.headers});if(url.pathname==='/api/site'){const content=await readContent(request);res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify(content));}if(url.pathname.startsWith('/api/'))return await handleAPI(req,res);if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);return res.end('Method not allowed');}
 if(url.pathname.startsWith('/assets/')||url.pathname.startsWith('/media/')||url.pathname.startsWith('/uploads/')||url.pathname==='/favicon.ico'){const uploads=url.pathname.startsWith('/uploads/'),directory=uploads?uploadsDirectory:root;let name=decodeURIComponent(url.pathname);if(uploads)name=name.slice('/uploads/'.length);else name=name.slice(1);if(name.includes('\\')||name.includes('\0'))throw Object.assign(Error('Invalid path'),{status:400});const file=path.resolve(directory,name),relative=path.relative(directory,file);if(relative.startsWith('..')||path.isAbsolute(relative))throw Object.assign(Error('Invalid path'),{status:403});const info=await stat(file);if(!info.isFile())throw Object.assign(Error('Not found'),{status:404});res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Content-Length':info.size,'Cache-Control':url.pathname.startsWith('/assets/')?'public, max-age=31536000, immutable':'public, max-age=3600'});if(req.method==='HEAD')return res.end();return await pipeline(createReadStream(file),res);}
 const content=await readContent(request),known=/^\/(?:worlds\/(?:survival\/|mod-1\/|mod-2\/)?)?$/.test(url.pathname)||/^\/(?:guide|community|downloads|admin)\/?$/.test(url.pathname)||/^\/community\/post\/[\w-]+\/?$/.test(url.pathname),admin=url.pathname.startsWith('/admin');const html=render(content,url.pathname),payload=JSON.stringify(content).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');const description=escape(content.site.description),canonical=escape(content.site.origin.replace(/\/$/,'')+url.pathname);const page=template.replace('<!--ssr-->',html).replace('<head>','<head><meta name="description" content="'+description+'"/><link rel="canonical" href="'+canonical+'"/>'+(admin||content.preview?'<meta name="robots" content="noindex,nofollow"/>':'')).replace('<script type="module"','<script>window.__SITE__='+payload+'</script><script type="module"');res.writeHead(known?200:404,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'; form-action 'self'"});res.end(req.method==='HEAD'?'':page);
 }catch(e){if(!res.headersSent){res.writeHead(e.status|| (e.code==='ENOENT'?404:500),{'Content-Type':'text/plain; charset=utf-8'});res.end(e.code==='ENOENT'?'未找到页面或文件':'网站暂时无法响应，请稍后重试。');}else res.destroy();if(e.code!=='ENOENT')console.error('[website]',e.message);}});
server.requestTimeout=30000;server.headersTimeout=15000;server.listen(port,host,()=>console.info(`幻想镇 NEXT 官网：http://${host}:${port}`));
