import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import {gzipSync} from 'node:zlib';
import {createCommunity} from '../src/server.mjs';
const i32=n=>{const b=Buffer.alloc(4);b.writeInt32BE(n);return b;};
const str=s=>{const b=Buffer.from(s),n=Buffer.alloc(2);n.writeUInt16BE(b.length);return Buffer.concat([n,b]);};
const tag=(type,name,value)=>Buffer.concat([Buffer.from([type]),str(name),value]);
export const schematic=gzipSync(Buffer.concat([Buffer.from([10,0,0]),tag(9,'size',Buffer.concat([Buffer.from([3]),i32(3),i32(1),i32(1),i32(1)])),tag(9,'palette',Buffer.concat([Buffer.from([10]),i32(1),tag(8,'Name',str('minecraft:stone')),Buffer.from([0])])),tag(9,'blocks',Buffer.concat([Buffer.from([10]),i32(1),tag(3,'state',i32(0)),tag(9,'pos',Buffer.concat([Buffer.from([3]),i32(3),i32(0),i32(0),i32(0)])),Buffer.from([0])])),Buffer.from([0])]));
test('blueprint review gates every download; roles can be revoked; forum ownership and moderation persist',async t=>{
  const data=await mkdtemp(path.join(tmpdir(),'hxz-content-')),service=createCommunity({data,adminIDs:['admin'],exchange:async i=>({selectedProfile:{id:i.accessToken,name:i.accessToken}})});
  service.server.listen(0,'127.0.0.1');await once(service.server,'listening');const base='http://127.0.0.1:'+service.server.address().port;
  t.after(async()=>{await service.close();await rm(data,{recursive:true,force:true});});
  const tokens={};
  async function request(p,method='GET',input,user){const r=await fetch(base+p,{method,headers:{'Content-Type':Buffer.isBuffer(input)?'application/octet-stream':'application/json',...(user?{Authorization:'Bearer '+tokens[user]}:{})},body:input===undefined?undefined:Buffer.isBuffer(input)?input:JSON.stringify(input)});return {status:r.status,value:r.headers.get('content-type')?.includes('json')?await r.json():Buffer.from(await r.arrayBuffer())};}
  for(const user of ['admin','alice','reviewer']) tokens[user]=(await request('/api/session','POST',{accessToken:user})).value.token;
  const metadata={title:'Stone machine',description:'Fixture',category:'生产与加工',mc:'1.21.1',loader:'neoforge',create_version:'6.0.6'};
  const id=(await request('/api/blueprints','POST',metadata,'alice')).value.id;
  assert.ok(id);
  assert.equal((await request('/api/blueprints/'+id+'/file','PUT',schematic,'reviewer')).status,403);
  assert.equal((await request('/api/blueprints/'+id+'/file','PUT',schematic,'alice')).status,200);
  assert.equal((await request('/api/blueprints')).value.total,0);
  assert.equal((await request('/api/blueprints/'+id)).status,403);
  assert.equal((await request('/api/blueprints/'+id+'/file')).status,403);
  assert.equal((await request('/api/blueprints/'+id+'/review','POST',{status:'approved'},'reviewer')).status,403);
  assert.equal((await request('/api/admin/reviewers','POST',{uid:'reviewer',enabled:true},'alice')).status,400);
  assert.equal((await request('/api/admin/reviewers','POST',{uid:'reviewer',enabled:true},'admin')).status,200);
  assert.equal((await request('/api/blueprints?scope=review','GET',undefined,'reviewer')).value.total,1);
  assert.deepEqual((await request('/api/blueprints/'+id,'GET',undefined,'reviewer')).value.metadata.dimensions,[1,1,1]);
  assert.equal((await request('/api/blueprints/'+id+'/review','POST',{status:'approved'},'reviewer')).status,200);
  assert.equal((await request('/api/blueprints')).value.total,1);
  assert.deepEqual((await request('/api/blueprints/'+id+'/file')).value,schematic);
  assert.equal((await request('/api/blueprints/'+id+'/file','PUT',schematic,'alice')).status,400,'approved file cannot be silently replaced');
  assert.equal((await request('/api/blueprints/'+id+'/review','POST',{status:'rejected',reason:'removed'},'reviewer')).status,200);
  assert.equal((await request('/api/blueprints/'+id+'/file')).status,403);
  await request('/api/admin/reviewers','POST',{uid:'reviewer',enabled:false},'admin');
  assert.equal((await request('/api/blueprints?scope=review','GET',undefined,'reviewer')).status,403,'existing token does not retain revoked role');
  const bad=(await request('/api/blueprints','POST',metadata,'alice')).value.id;
  assert.equal((await request('/api/blueprints/'+bad+'/file','PUT',Buffer.from('not NBT'),'alice')).status,400);
  assert.equal((await request('/api/blueprints')).value.total,0);
  const post=(await request('/api/forum/posts','POST',{title:'Hello',body:'text <script>not executable</script>',category:'交流讨论',uid:'admin'},'alice')).value.id;
  assert.equal((await request('/api/forum/posts/'+post)).value.post.uid,'alice');
  await request('/api/forum/posts/'+post+'/replies','POST',{body:'reply'},'reviewer');
  for(let i=0;i<2;i++)assert.equal((await request('/api/forum/posts/'+post+'/like','PUT',{liked:true},'reviewer')).value.likes,1);
  assert.equal((await request('/api/forum/posts/'+post,'DELETE',undefined,'reviewer')).status,403);
  assert.equal((await request('/api/forum/posts/'+post+'/moderate','POST',{action:'locked',value:true},'reviewer')).status,400);
  await request('/api/forum/posts/'+post+'/moderate','POST',{action:'locked',value:true},'admin');
  assert.equal((await request('/api/forum/posts/'+post+'/replies','POST',{body:'blocked'},'reviewer')).status,400);
  await request('/api/forum/posts/'+post+'/moderate','POST',{action:'hidden',value:true},'admin');
  assert.equal((await request('/api/forum/posts/'+post)).status,404);
  assert.equal((await request('/api/forum/posts')).value.total,0);
  assert.equal((await request('/api/forum/posts?manage=1','GET',undefined,'admin')).value.total,1);
  await request('/api/forum/posts/'+post,'DELETE',undefined,'admin');
  assert.equal(service.db.prepare('SELECT COUNT(*) AS n FROM forum_replies').get().n,0);
  assert.equal(service.db.prepare('SELECT COUNT(*) AS n FROM forum_likes').get().n,0);
});
