<script setup lang="ts">
import {ref,computed,watch} from 'vue';
import {state,task,invoke,perform} from '../lib/launcher';
const instance=ref(state.settings.selectedInstance),kind=ref('resourcepack'),query=ref(''),world=ref(''),worlds=ref<string[]>([]),loading=ref(false),note=ref(''),offset=ref(0),total=ref(0);
const items=ref<{project_id:string;title:string;description:string;icon_url?:string}[]>([]);
const instances=computed(()=>state.instances.filter(i=>!i.placeholder&&!i.error).map(i=>({label:i.name||i.id,value:i.id})));
watch([instance,kind],async()=>{items.value=[];world.value='';worlds.value=[];if(kind.value==='datapack'&&instance.value)await perform(async()=>{worlds.value=await invoke('addons.worlds',{instance:instance.value});});});
async function search(page=0){loading.value=true;try{const result=await invoke<{hits:typeof items.value;total_hits:number}>('addons.search',{instance:instance.value,kind:kind.value,query:query.value,offset:page});items.value=result.hits;total.value=result.total_hits;offset.value=page;}finally{loading.value=false;}}
async function install(project:string){const result=await invoke<{hint:string}>('addons.install',{instance:instance.value,kind:kind.value,world:world.value,project});note.value=result.hint;}
</script>
<template><section class="panel settings-section"><div class="install-grid"><q-select v-model="instance" :options="instances" emit-value map-options outlined label="目标实例"/><q-select v-model="kind" :options="[{label:'资源包',value:'resourcepack'},{label:'光影包',value:'shader'},{label:'数据包',value:'datapack'}]" emit-value map-options outlined label="资源类型"/><q-select v-if="kind==='datapack'" v-model="world" :options="worlds" outlined label="目标存档"/><q-input v-model="query" outlined label="搜索名称" @keyup.enter="perform(()=>search())"/></div><div class="row q-mt-md"><q-btn class="primary-button" unelevated icon="search" label="查找兼容资源" :loading="loading" :disable="!instance" @click="perform(()=>search())"/></div><p v-if="note" role="status">{{note}}</p><div class="catalog-list q-mt-md"><div v-for="item in items" :key="item.project_id" class="panel catalog-item"><img v-if="item.icon_url" :src="item.icon_url" width="36" height="36" loading="lazy" alt=""/><span><strong>{{item.title}}</strong><small>{{item.description}}</small></span><q-btn outline label="安装" :disable="task.busy||state.running||(kind==='datapack'&&!world)" @click="perform(()=>install(item.project_id))"/></div></div><div class="row q-gutter-sm q-mt-md"><q-btn flat label="上一页" :disable="!offset||loading" @click="perform(()=>search(offset-20))"/><span>{{items.length?offset+1:0}}–{{offset+items.length}} / {{total}}</span><q-btn flat label="下一页" :disable="offset+20>=total||loading" @click="perform(()=>search(offset+20))"/></div></section></template>
