<script setup>
import {ref,onMounted} from 'vue';
const props=defineProps({request:{type:Function,required:true},diagnosticProvider:Function});
const categories={community:'社区',launcher:'启动器',server:'服务器',crash:'游戏崩溃'},statuses={open:'待处理',working:'处理中',resolved:'已解决'};
const list=ref({items:[],total:0,manager:false}),scope=ref('mine'),offset=ref(0),detail=ref(null),editing=ref(false),busy=ref(false),error=ref('');
const form=ref({category:'launcher',title:'',body:'',report:''}),reply=ref('');
async function run(fn){busy.value=true;error.value='';try{await fn();}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function load(){list.value=await props.request('/api/feedback?scope='+scope.value+'&offset='+offset.value);}
async function open(id){detail.value=await props.request('/api/feedback/'+id);reply.value='';}
async function submit(){const r=await props.request('/api/feedback','POST',form.value);editing.value=false;form.value={category:'launcher',title:'',body:'',report:''};await open(r.id);await load();}
async function respond(status){await props.request('/api/feedback/'+detail.value.item.id,'POST',{body:reply.value,...(status?{status}:{})});await open(detail.value.item.id);await load();}
onMounted(()=>run(load));
</script>
<template><section class="feedback-panel">
 <header><h2>问题反馈</h2><div><button :disabled="busy" @click="run(load)">刷新</button><button @click="editing=!editing;detail=null">提交反馈</button></div></header>
 <p v-if="error" role="alert">{{error}}</p>
 <div v-if="editing" class="feedback-form"><div class="feedback-tabs"><button v-for="(name,id) in categories" :key="id" :class="{active:form.category===id}" @click="form.category=id">{{name}}</button></div><label>标题<input v-model="form.title" maxlength="100"></label><label>现象、发生时间与复现步骤<textarea v-model="form.body" rows="5" maxlength="8000"/></label><button v-if="diagnosticProvider" :disabled="busy" @click="run(async()=>form.report=await diagnosticProvider())">附上最近一次崩溃诊断</button><label v-if="form.report">待发送的诊断（可检查和删除敏感内容）<textarea v-model="form.report" rows="5" maxlength="64000"/></label><button :disabled="busy||form.title.trim().length<2||form.body.trim().length<5" @click="run(submit)">发送给管理员</button></div>
 <article v-else-if="detail"><button @click="detail=null">← 返回反馈列表</button><h3>{{detail.item.title}}</h3><small>{{categories[detail.item.category]}} · {{statuses[detail.item.status]}} · {{detail.item.name}}</small><p class="feedback-body">{{detail.item.body}}</p><details v-if="detail.item.report"><summary>附加诊断</summary><pre>{{detail.item.report}}</pre></details><div v-for="(item,i) in detail.replies" :key="i" class="feedback-reply"><small>{{item.manager?'管理员 · ':''}}{{item.name}} · {{new Date(item.created).toLocaleString()}}</small><p class="feedback-body">{{item.body}}</p></div><textarea v-model="reply" maxlength="8000" rows="3" placeholder="补充信息或回复"/><button :disabled="busy||!reply.trim()" @click="run(()=>respond())">回复</button><div v-if="detail.manager" class="feedback-tabs"><button v-for="(name,id) in statuses" :key="id" :disabled="busy" @click="run(()=>respond(id))">标记{{name}}</button></div></article>
 <template v-else><div v-if="list.manager" class="feedback-tabs"><button v-for="(name,id) in {mine:'我的反馈',all:'管理员收件箱'}" :key="id" :class="{active:scope===id}" @click="scope=id;offset=0;run(load)">{{name}}</button></div><p v-if="!list.items.length">暂无反馈</p><button v-for="item in list.items" :key="item.id" class="feedback-item" @click="run(()=>open(item.id))"><strong>{{item.title}}</strong><small>{{categories[item.category]}} · {{statuses[item.status]}} · {{item.name}}</small></button><footer><button :disabled="busy||!offset" @click="offset-=20;run(load)">上一页</button><span>{{list.total?offset+1:0}}–{{Math.min(offset+20,list.total)}} / {{list.total}}</span><button :disabled="busy||offset+20>=list.total" @click="offset+=20;run(load)">下一页</button></footer></template>
</section></template>
<style scoped>
.feedback-panel{min-width:0;color:var(--text);padding:16px;background:var(--surface,var(--panel));border:1px solid var(--line,var(--border));border-radius:14px}.feedback-panel header,.feedback-panel footer,.feedback-tabs{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.feedback-panel button{font:inherit;min-height:40px;border:1px solid var(--line,var(--border));border-radius:9px;padding:8px 12px;background:var(--soft,var(--panel));color:inherit;cursor:pointer}.feedback-panel button:disabled{opacity:.45}.feedback-panel h3{margin:14px 0}.feedback-form{display:grid;gap:12px;margin-top:14px}.feedback-form label{display:grid;gap:8px}.feedback-panel input,.feedback-panel textarea{width:100%;min-width:0;box-sizing:border-box;font:inherit;border:1px solid var(--line,var(--border));border-radius:9px;padding:10px;color:inherit;background:var(--bg,var(--panel))}.feedback-panel small{display:block;opacity:.75;font-size:.8rem}.feedback-body,.feedback-panel pre{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.7}.feedback-panel pre{max-height:250px;overflow:auto;font-size:.75rem}.feedback-item{display:grid;width:100%;text-align:left;gap:6px;margin:10px 0}.feedback-reply{margin:12px 0;padding:12px;border-left:3px solid var(--accent);background:var(--soft)}.feedback-tabs{justify-content:flex-start;margin:12px 0}.feedback-tabs .active{border-color:var(--accent);color:var(--accent)}
</style>
