<script setup>
import {ref,onMounted} from 'vue';
const props=defineProps({request:{type:Function,required:true}});
const wallet=ref({balance:'0',ledger:[],total:0}),offset=ref(0),code=ref(''),busy=ref(false),error=ref(''),notice=ref('');
async function load(){busy.value=true;error.value='';try{const value=await props.request('/api/points?offset='+offset.value);if(!Array.isArray(value?.ledger)||value.balance==null)throw Error('积分数据暂时不可用，请刷新重试');wallet.value={...value,ledger:value.ledger.map(entry=>({...entry,amount:String(entry.amount??0)}))};}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function redeem(){if(busy.value||!code.value.trim())return;busy.value=true;error.value='';try{await props.request('/api/points/redeem','POST',{code:code.value.trim()});code.value='';offset.value=0;notice.value='兑换成功';await load();}catch(e){error.value=e.message;}finally{busy.value=false;}}
onMounted(load);
</script>
<template><section class="wallet-card"><header><div><small>可用积分</small><strong>{{wallet.balance}}</strong></div><button :disabled="busy" @click="load">刷新</button></header><p>商城消费只扣余额，不减少已经获得的榜单积分。</p><form @submit.prevent="redeem"><input v-model="code" placeholder="输入积分兑换码" aria-label="积分兑换码" autocomplete="off"/><button :disabled="busy||!code.trim()">兑换</button></form><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><details><summary>收支明细 · {{wallet.total}} 笔</summary><ol><li v-for="entry in wallet.ledger" :key="entry.id"><div><b>{{entry.reason}}</b><small>{{new Date(entry.created).toLocaleString('zh-CN')}}</small></div><strong :class="{incoming:!entry.amount.startsWith('-')}">{{entry.amount.startsWith('-')?'':'+'}}{{entry.amount}}</strong></li></ol><p v-if="!wallet.ledger.length">暂无收支记录</p><footer><button :disabled="!offset||busy" @click="offset=Math.max(0,offset-30);load()">上一页</button><span>{{Math.floor(offset/30)+1}} / {{Math.max(1,Math.ceil(wallet.total/30))}}</span><button :disabled="offset+30>=wallet.total||busy" @click="offset+=30;load()">下一页</button></footer></details></section></template>
<style scoped>.wallet-card{margin:20px 0;padding:22px;border:1px solid var(--border,var(--line));border-radius:16px;background:var(--panel,var(--surface));color:var(--text);min-width:0}.wallet-card header,.wallet-card footer{display:flex;align-items:center;justify-content:space-between;gap:12px}.wallet-card header small{display:block;color:var(--muted)}.wallet-card header strong{font-size:2rem;overflow-wrap:anywhere}.wallet-card p{color:var(--muted);line-height:1.7;font-size:.85rem}.wallet-card form{display:flex;gap:10px;margin:16px 0}.wallet-card input{flex:1;min-width:0;background:transparent;border:1px solid var(--border,var(--line));border-radius:8px;padding:12px;color:inherit;font:inherit}.wallet-card button{border:1px solid var(--border,var(--line));padding:9px 14px;border-radius:9px;color:inherit;background:var(--panel,var(--surface));font:inherit;cursor:pointer}.wallet-card button:disabled{opacity:.45}.wallet-card summary{cursor:pointer;padding:10px 0}.wallet-card ol{padding:0;list-style:none}.wallet-card li{display:flex;gap:16px;padding:12px 0;border-bottom:1px solid var(--border,var(--line));align-items:center}.wallet-card li>div{flex:1;min-width:0;overflow-wrap:anywhere}.wallet-card li small{display:block;color:var(--muted);margin-top:5px}.wallet-card li strong{max-width:40%;overflow-wrap:anywhere}.incoming{color:var(--accent)}</style>
