import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {spawn,execFileSync} from 'node:child_process';import {once} from 'node:events';import assert from 'node:assert/strict';
import {download,configureDownloads,hash,writeJSON} from '../../packages/engine/core/io.mjs';
import {setDownloadMode} from '../../packages/engine/core/sources.mjs';
const dir=await fs.mkdtemp(path.resolve('.runtime/limit064-')),small=Buffer.alloc(256*1024,41),large=Buffer.alloc(4*1024*1024,17),sha=b=>createHash('sha1').update(b).digest('hex');let requests=[];
const server=http.createServer((req,res)=>{requests.push(req.url);if(req.url.startsWith('/broken')){res.writeHead(503);res.end();return;}const data=req.url.startsWith('/large')?large:small,m=/bytes=(\d+)-(\d*)/.exec(req.headers.range||'');if(m){const start=+m[1],end=m[2]?+m[2]:data.length-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${data.length}`,'Content-Length':end-start+1});res.end(data.subarray(start,end+1));}else{res.setHeader('Content-Length',data.length);res.end(data);}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const options={size:small.length,sha1:sha(small),retryBudgetMs:500,stallWindowMs:150};
try{
 setDownloadMode('official');configureDownloads({concurrency:32,speedLimitMBps:.25});let start=Date.now();
 await Promise.all([1,2].map(i=>download(base+'/official'+i,dir+'/node'+i,options)));let elapsed=Date.now()-start;assert(elapsed>=1750&&elapsed<6000,'合计限速应约 2 秒，实际 '+elapsed);console.log('PASS Node aggregate limit:',elapsed,'ms for 512 KB / 0.25 MB/s');
 configureDownloads({speedLimitMBps:0});requests=[];await download(base+'/official',dir+'/preferred',{...options,urls:[base+'/official',base+'/mirror']});assert.deepEqual(requests,['/official']);requests=[];await download(base+'/broken',dir+'/fallback',{...options,urls:[base+'/broken',base+'/mirror']});assert.deepEqual(requests,['/broken','/mirror']);console.log('PASS official success does not contact mirror; failure falls back and verifies hash');
 configureDownloads({speedLimitMBps:4});start=Date.now();await download(base+'/large',dir+'/ranges',{size:large.length,sha1:sha(large),stallWindowMs:150});elapsed=Date.now()-start;assert(elapsed>780&&elapsed<4000);assert.equal(await hash(dir+'/ranges'),sha(large));console.log('PASS ranges share the same byte limit:',elapsed,'ms');
 configureDownloads({speedLimitMBps:.25});start=Date.now();const running=download(base+'/large',dir+'/live',{size:large.length,sha1:sha(large),segmentThreshold:Infinity});setTimeout(()=>configureDownloads({speedLimitMBps:0}),250);await running;assert(Date.now()-start<2000);console.log('PASS removing limit wakes all queued transfers');
 configureDownloads({speedLimitMBps:.25});const abort=new AbortController(),cancelled=download(base+'/large',dir+'/cancel',{size:large.length,sha1:sha(large),signal:abort.signal});setTimeout(()=>abort.abort(Error('fixture cancel')),100);await assert.rejects(cancelled);configureDownloads({speedLimitMBps:0});
 const jdk=path.join(process.env.JAVA_HOME||'C:/Program Files/Java/jdk-21','bin'),cp=path.resolve('resources/installer/game-installer.jar')+path.delimiter+path.resolve('resources/hxzup/updater-1.0.3.jar');
 await fs.writeFile(dir+'/Limit.java',`package up.hxz;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;public class Limit{public static void main(String[] a)throws Exception{Network n=new Network(2,0,32);ExecutorService e=Executors.newFixedThreadPool(2);try{List<Future<?>> jobs=new ArrayList<>();for(int i=0;i<2;i++){final int id=i;jobs.add(e.submit(()->{try{Path d=Paths.get(a[1],"job"+id);Files.createDirectories(d);Path p=n.race(Arrays.asList(a[0]+"/official"+id),d,a[2],262144);if(Files.size(p)!=262144)throw new Exception("bad size");}catch(Exception x){throw new RuntimeException(x);}}));}for(Future<?> j:jobs)j.get();System.out.println("verified");}finally{e.shutdownNow();}}}`);
 execFileSync(path.join(jdk,'javac.exe'),['--release','8','-encoding','UTF-8','-cp',cp,'-d',dir,dir+'/Limit.java'],{windowsHide:true,stdio:'pipe'});
 async function javaTest(live){const config=dir+'/中文限速.json';await writeJSON(config,{bytesPerSecond:262144});const t=Date.now(),child=spawn(path.join(jdk,'java.exe'),['-Dhxz.download.limitBytes=262144','-Dhxz.download.limitFile64='+Buffer.from(config).toString('base64'),'-Dhxz.download.stallMillis=150','-cp',cp+path.delimiter+dir,'up.hxz.Limit',base,dir+'/java'+live,sha(small)],{windowsHide:true});let text='';child.stdout.on('data',b=>text+=b);child.stderr.on('data',b=>text+=b);const stop=setTimeout(()=>child.kill(),8000),change=live?setTimeout(()=>void writeJSON(config,{bytesPerSecond:0}),250):null;const [code]=await once(child,'close');clearTimeout(stop);clearTimeout(change);assert.equal(code,0,text);return Date.now()-t;}
 elapsed=await javaTest(false);assert(elapsed>1750&&elapsed<6000);console.log('PASS Java aggregate limit and no false low-speed fallback:',elapsed,'ms');elapsed=await javaTest(true);assert(elapsed<1800);console.log('PASS Java live unlimited change through Chinese config path:',elapsed,'ms');
}finally{configureDownloads({speedLimitMBps:0});server.closeAllConnections();server.close();}
