import {createRenderer} from './arcade-renderer.mjs';
import {mountGameControls} from './game-controls.mjs';
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountTankRoom(root,{request,send,subscribe}){
 let room=null,uid='',items=[],busy=false,error='',title='',code='',closed=false,seq=0,keys=new Set(),renderer,controls,raf=0,screen='',last=0,loading=false,confirm=false,generation=0;
 root.classList.add('coop-game');let focused=false,anchor=null;
 function focus(value){if(value===focused)return;focused=value;root.classList.toggle('coop-focus',value);if(value){anchor=document.createComment('coop-position');root.before(anchor);document.body.append(root);}else if(anchor){anchor.replaceWith(root);anchor=null;}const b=root.querySelector('[data-room-action="focus"]');if(b)b.textContent=value?'退出专注':'专注游玩';}

 const button=(t,a,disabled=false)=>`<button type="button" data-room-action="${a}" ${disabled?'disabled':''}>${t}</button>`;
 function transmit(){if(!room||closed)return;try{const value=send({id:room.id,seq:++seq,keys:[...keys].slice(-3)});value?.catch?.(e=>{error='社区连接中断，正在等待重新连接';status();});}catch(e){error=e.message;status();}}
 function release(){keys.clear();transmit();}
 const inputApi={mode:{value:'solo'},release(a){keys.delete(a);transmit();},hold(a){if(room?.phase!=='playing')return;if(a!=='fire')for(const k of [...keys])if(k!=='fire')keys.delete(k);keys.add(a);transmit();},input(a){if(room?.phase!=='playing')return;keys.add(a);transmit();setTimeout(()=>{keys.delete(a);transmit();},100);}};
 async function act(action,id){if(busy||closed)return;busy=true;error='';const gen=++generation;try{const data=await request(action==='create'?'/api/coop/tanks':'/api/coop/tanks/'+(id||room?.id),'POST',action==='create'?{title}:{action});if(closed||gen!==generation)return;if(data.left){room=null;screen='';release();}else{room=data.room;uid=data.uid;transmit();}confirm=false;render();if(room?.phase==='playing')focus(true);if(!room)focus(false);}catch(e){error=e.message;status();}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);void refresh();}}
 function accept(value){if(closed||!room||value.room?.id!==room.id)return;const before=room;room=value.room;last=performance.now();if(room.phase!=='playing')keys.clear();if(before.phase!==room.phase){render();if(room.phase==='playing')focus(true);}else status();}
 const unsub=subscribe(accept);
 async function refresh(){if(closed||busy||loading||document.hidden)return;loading=true;const gen=generation,id=room?.id;try{const data=await request('/api/coop/tanks'+(id?'/'+id:''));if(closed||gen!==generation||id!==room?.id)return;if(id){uid=data.uid;accept(data);}else{items=data.items||[];render();}}catch(e){error=e.message;status();}finally{loading=false;}}
 function status(){if(closed)return;const e=root.querySelector('.coop-error');if(e){e.textContent=error;e.hidden=!error;}if(!room)return;const me=room.members.findIndex(m=>m.uid===uid),v=root.querySelector('.coop-vitals');if(v)v.textContent='第 '+room.state.level+' / 20 波 · '+room.state.score+' 分 · 基地 '+room.state.lives+'/6';const seats=root.querySelector('.coop-members');if(seats)seats.innerHTML=Array.from({length:2},(_,i)=>{const m=room.members[i];return `<span class="${me===i?'self':''}"><i class="player-${i}"></i>${m?safe(m.name):'等待伙伴'}<small>${m?(m.online?'已连接':'连接中')+(room.phase==='waiting'?(m.ready?' · 已准备':' · 未准备'):' · 生命 '+room.state.players[i].hp+'/3'):''}</small></span>`;}).join('');const note=root.querySelector('.coop-phase');if(note)note.textContent=room.reason||({waiting:'把房间号分享给伙伴，双方准备后开始。',playing:'你只控制自己的坦克，另一辆由伙伴操控。',paused:'游戏已暂停',finished:room.state.won?'二十轮防线全部守住了！':'本局结束'})[room.phase];const lag=root.querySelector('.coop-lag');if(lag)lag.textContent=room.phase==='playing'&&performance.now()-last>2000?'正在等待社区同步…':'';}
 function render(){if(closed)return;const next=room?'room:'+room.id+':'+room.phase+':'+(room.members.find(m=>m.uid===uid)?.ready?'ready':'wait'):'lobby';if(next===screen){status();const list=root.querySelector('.coop-room-list');if(list)list.innerHTML=roomList();return;}screen=next;renderer?.dispose();renderer=null;controls?.();controls=null;const focus=root.contains(document.activeElement)?document.activeElement?.dataset.field:null;
 root.innerHTML='<p class="coop-error" role="alert" hidden></p>';
 if(!room){root.innerHTML+=`<div class="coop-lobby"><section class="coop-card"><small>10 · 双人联网合作</small><h2>星堡双卫</h2><p>两位玩家，两台设备。一起守住星灯基地。</p><label>房间名称<input data-field="title" maxlength="40" value="${safe(title)}" placeholder="给防线起个名字"/></label>${button('创建合作房间','create')}<div class="coop-invite"><input data-field="code" maxlength="8" value="${safe(code)}" placeholder="输入伙伴的房间号" aria-label="房间号"/>${button('加入','join-code')}</div><small>电脑与手机可一起玩，使用当前社区连接。</small></section><section class="coop-card"><header><h3>正在等待伙伴</h3>${button('刷新','refresh')}</header><div class="coop-room-list">${roomList()}</div></section></div>`;}
 else{const me=room.members.find(m=>m.uid===uid);root.innerHTML+=`<section class="coop-card coop-room"><header><div><small>房间 ${safe(room.id)}</small><h2>${safe(room.title)}</h2></div><div class="coop-actions">${button(focused?'退出专注':'专注游玩','focus')}${button('离开房间','leave')}</div></header><div class="coop-members"></div><div class="coop-vitals"></div><div class="coop-play-layout"><div class="coop-stage"><canvas tabindex="0" aria-label="联网坦克游戏画面"></canvas>${room.phase==='playing'?'':`<div class="coop-overlay"><h3>${{waiting:'等待伙伴',paused:'已暂停',finished:room.state.won?'合作通关':'本局结束'}[room.phase]}</h3><p>${room.phase==='finished'?room.state.score+' 分':room.phase==='waiting'?'每人使用自己的电脑或手机加入':'进度已保存，等待两端连接'}</p></div>`}</div><div class="coop-interaction"><p class="coop-phase"></p><div class="coop-actions">${room.phase==='waiting'?button(me?.ready?'取消准备':'准备','ready')+(room.host===uid?button('开始合作','start'):''):room.phase==='playing'?button('暂停','pause'):room.phase==='paused'?button('继续合作','resume'):''}</div><div class="coop-input"></div><p class="coop-lag" role="status"></p><small>WASD / 方向键移动 · J / 空格开火<br/>切到后台自动暂停；断线会为双方保留进度。</small></div></div></section>`;renderer=createRenderer(root.querySelector('canvas'),'tanks');renderer.draw(room.state);if(room.phase==='playing')controls=mountGameControls(root.querySelector('.coop-input'),inputApi,'tanks');}
 if(confirm)root.innerHTML+=`<div class="coop-confirm" role="alert"><p>离开会结束正在进行的合作，确定离开？</p>${button('留下','stay')}${button('确认离开','confirm-leave')}</div>`;
 if(focus)root.querySelector('[data-field="'+focus+'"]')?.focus({preventScroll:true});status();}
 function roomList(){return items.length?items.map(r=>`<article><div><strong>${safe(r.title)}</strong><small>${safe(r.id)} · ${r.count}/2 人</small></div><button data-room-action="join" data-id="${safe(r.id)}">${r.joined?'返回房间':'加入'}</button></article>`).join(''):'<p class="coop-empty">还没有等待中的房间，可以邀请伙伴开一局。</p>';}
 const click=e=>{const b=e.target.closest('[data-room-action]');if(!b||busy)return;const a=b.dataset.roomAction;if(a==='focus')focus(!focused);else if(a==='refresh')void refresh();else if(a==='join')void act('join',b.dataset.id);else if(a==='join-code'){if(/^[A-F\d]{8}$/i.test(code.trim()))void act('join',code.trim().toUpperCase());else{error='请输入 8 位房间号';status();}}else if(a==='create')void act(a);else if(a==='leave'){if(room.phase==='waiting'||room.phase==='finished')void act('leave');else{confirm=true;const box=document.createElement('div');box.className='coop-confirm';box.innerHTML='<p>离开会结束本局合作，确定离开？</p>'+button('留下','stay')+button('确认离开','confirm-leave');root.querySelector('.coop-confirm')?.remove();root.append(box);}}else if(a==='stay'){confirm=false;root.querySelector('.coop-confirm')?.remove();}else if(a==='confirm-leave')void act('leave');else void act(a);};
 const change=e=>{if(e.target.dataset.field==='title')title=e.target.value;if(e.target.dataset.field==='code')code=e.target.value;};
 const key=e=>{if(room?.phase!=='playing'||e.target?.closest('input,textarea,[contenteditable]'))return;const a={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',KeyJ:'fire',Space:'fire'}[e.code];if(!a)return;e.preventDefault();if(e.type==='keyup')inputApi.release(a);else if(!e.repeat)inputApi.hold(a);};
 const hidden=()=>{release();if(room?.phase==='playing')void act('pause');};
 const visibility=()=>{if(document.hidden)hidden();};
 function frame(){if(closed)return;if(renderer&&room){renderer.draw(room.state,1,performance.now());if(performance.now()-last>2000)status();}raf=requestAnimationFrame(frame);}
 root.addEventListener('click',click);root.addEventListener('input',change);window.addEventListener('keydown',key,true);window.addEventListener('keyup',key,true);window.addEventListener('blur',hidden);document.addEventListener('visibilitychange',visibility);
 const heartbeat=setInterval(transmit,350),poll=setInterval(refresh,3000);render();void refresh();frame();
 return ()=>{focus(false);release();closed=true;generation++;clearInterval(heartbeat);clearInterval(poll);cancelAnimationFrame(raf);controls?.();renderer?.dispose();unsub();root.removeEventListener('click',click);root.removeEventListener('input',change);window.removeEventListener('keydown',key,true);window.removeEventListener('keyup',key,true);window.removeEventListener('blur',hidden);document.removeEventListener('visibilitychange',visibility);root.replaceChildren();};
}
