<script setup>
import {ref} from 'vue';
import BoardGames from './BoardGames.vue';
import PointsPanel from './PointsPanel.vue';
import {BOARD_GAMES} from '../../../server/shared/board-catalog.mjs';
const boardGame=ref(null),pointsOpen=ref(false);
import {useArcade} from '../lib/use-arcade.mjs';
const props=defineProps({request:{type:Function,required:true}});
const {rankPeriod,changeRank,syncPaused,retrySync,GAMES,selected,canvas,game,score,playing,paused,busy,message,ranking,rankSelf,rankLabel,rankError,ranked,finished,countdown,level,lines,sound,pendingScore,best,name,time,thumbnail,select,toggleSound,start,input,hold,release,pause,submit,finish,pointer}=useArcade((...args)=>props.request(...args));
</script>
<template>
 <section class="arcade-page" :data-arcade-playing="playing" :style="{'--game-color':selected?.color||'#9dd9a8'}">
  <header v-if="!boardGame&&!pointsOpen" class="arcade-heading"><div><span class="arcade-eyebrow">FANTASY TOWN · ARCADE</span><h1>{{name}}</h1></div><div class="arcade-top-actions"><button v-if="selected" @click="toggleSound" :aria-pressed="sound">{{sound?'音效开':'音效关'}}</button><button v-if="selected&&!playing&&!busy" @click="selected=null;game=null">游戏库 ↗</button><span v-if="!selected" class="arcade-counter">06 <small>款游戏</small></span></div></header>
  <div v-if="!selected&&!boardGame" class="arcade-library-tabs"><button @click="pointsOpen=!pointsOpen">{{pointsOpen?'返回游戏库':'积分榜与兑换'}} →</button></div>
  <PointsPanel v-if="pointsOpen" :request="request"/>
  <template v-else-if="boardGame"><div class="arcade-library-tabs"><button @click="boardGame=null">← 游戏库</button><span>社区棋牌 · {{boardGame.name}}</span></div><BoardGames :game="boardGame" :request="request"/></template>
  <div v-else-if="!selected" class="arcade-cards"><button v-for="(item,index) in GAMES" :key="item.id" class="arcade-card" @click="select(item)" :style="{'--game-color':item.color}"><div class="arcade-art" :class="item.id"><canvas :ref="el=>thumbnail(el,item)" aria-hidden="true"/><span class="arcade-card-number">0{{index+1}}</span><span class="arcade-card-play">▶</span></div><div class="arcade-card-body"><small>{{item.tag}}</small><strong>{{item.name}}</strong><span>{{item.description}}</span><footer><span>本机最佳 <b>{{best[item.id]||'—'}}</b></span><span>开始游戏 ↗</span></footer></div></button><button v-for="(item,index) in BOARD_GAMES" :key="item.id" class="arcade-card strategy-card" @click="boardGame=item" :style="{'--game-color':item.color}"><div class="arcade-art strategy-art" :class="item.id"><span class="strategy-symbol">{{item.symbol}}</span><span class="arcade-card-number">0{{index+4}}</span><span class="arcade-card-play">▶</span></div><div class="arcade-card-body"><small>{{item.tag}}</small><strong>{{item.name}}</strong><span>{{item.description}}</span><footer><span>社区联机 · 五档机器人</span><span>入座 ↗</span></footer></div></button></div>
  <div v-else-if="selected" class="arcade-layout" :class="selected.id"><section class="arcade-play">
   <div class="arcade-status"><div><small>本局得分</small><strong>{{score.toLocaleString()}}</strong></div><div><small>{{selected.id==='runner'?'用时':selected.id==='blocks'?'等级':'关卡'}}</small><b>{{selected.id==='runner'?time:String(level).padStart(2,'0')}}</b></div><div><small>{{selected.id==='blocks'?'消除行':'本机最佳'}}</small><b>{{selected.id==='blocks'?lines:best[selected.id]||'—'}}</b></div><button v-if="playing" class="arcade-pause" @click="pause">{{paused?'继续 ▶':'暂停 Ⅱ'}}</button></div>
   <div class="arcade-stage"><canvas v-if="game" ref="canvas" tabindex="0" :aria-label="selected.name" @pointerdown.prevent="pointer" @pointermove.prevent="pointer"/><canvas v-else :ref="el=>thumbnail(el,selected)" aria-hidden="true"/>
    <div v-if="!game||paused||finished||countdown" class="arcade-overlay" :class="{countdown:countdown&&!paused}">
     <template v-if="countdown&&!paused"><strong class="count-number">{{countdown}}</strong><span>准备出发</span></template>
     <template v-else-if="paused"><span class="overlay-symbol">Ⅱ</span><h2>休息一下</h2><p>{{syncPaused?'等待成绩同步，进度已保留':'当前进度已暂停'}}</p><button class="arcade-primary" @click="pause">{{syncPaused?'重试同步':'继续游戏'}}</button><button class="arcade-quiet" @click="finish">结束本局</button></template>
     <template v-else-if="finished"><span class="overlay-kicker">{{game.won?'全部通关':'挑战完成'}}</span><strong class="result-score">{{score.toLocaleString()}}</strong><p>{{time}} · {{ranked?'社区排位':'本机练习'}}</p><button class="arcade-primary" :disabled="busy" @click="start">{{busy?'正在提交…':'再来一局 ↗'}}</button><button v-if="pendingScore&&!busy" class="arcade-quiet" @click="submit">重试提交成绩</button></template>
     <template v-else><span class="overlay-kicker">{{selected.tag}}</span><h2>{{selected.name}}</h2><button class="arcade-primary" :disabled="busy" @click="start">{{busy?'准备中…':'开始游戏'}}</button></template>
    </div>
   </div>
   <div v-if="playing&&!paused" class="arcade-controls"><button v-if="selected.id==='runner'" @pointerdown.prevent="input('jump')">跳跃 <kbd>SPACE</kbd></button><template v-else><button @pointerdown.prevent="hold('left')" @pointerup="release('left')" @pointerleave="release('left')" @pointercancel="release('left')">←</button><template v-if="selected.id==='blocks'"><button @pointerdown.prevent="input('rotate')">旋转 ↻</button><button @pointerdown.prevent="input('hold')">暂存</button><button @pointerdown.prevent="input('drop')">落下 ↓</button></template><button @pointerdown.prevent="hold('right')" @pointerup="release('right')" @pointerleave="release('right')" @pointercancel="release('right')">→</button></template></div>
   <div class="arcade-footnote"><span><i :class="{practice:!ranked}"/>{{playing||finished?(ranked?'社区排位':'本机练习'):'登录社区后成绩自动参与排名'}}</span><button v-if="playing" class="arcade-quiet" @click="finish">结束本局</button></div><p v-if="message" class="arcade-message" role="status">{{message}}</p>
  </section><aside class="arcade-side"><section class="arcade-board"><header><h2>{{rankPeriod==='all'?'长期排行榜':'本周排行榜'}}</h2><span class="arcade-live">实时</span></header><div class="arcade-library-tabs"><button :aria-pressed="rankPeriod==='week'" @click="changeRank('week')">周榜</button><button :aria-pressed="rankPeriod==='all'" @click="changeRank('all')">长期榜</button></div><p v-if="rankError" role="status" class="arcade-empty">{{rankError}}</p><p v-else-if="!ranking.length" class="arcade-empty">首个纪录，等你创造。</p><ol><li v-for="(item,index) in ranking" :key="item.uid" :class="{podium:index<3}"><b>{{String(index+1).padStart(2,'0')}}</b><span>{{item.name}}</span><strong>{{item.score.toLocaleString()}}</strong></li></ol><footer>{{rankLabel}}<br>我的排名：{{rankSelf?.rank||'暂未上榜'}} · {{rankSelf?.score||0}} 分<br>每 5 秒同步 · 显示前十与本人</footer></section><section class="arcade-guide"><h2>操作指南</h2><p>{{selected.keys}}</p><p v-if="selected.id==='blocks'">虚线标记落点；暂存每块可用一次。每消除 10 行提升一级，连续消行可获额外分数。</p><p v-if="selected.id==='breakout'">挡板不同位置会改变反弹角度。连续击碎砖块获得连击加分，共 100 关、三次机会。金属砖不可破坏；击碎增益砖获得加宽、减速或护盾。</p><p v-if="selected.id==='runner'">点击画面也能跳跃。无时间上限，速度更快递增，注意提前观察障碍间距。</p><small>P / ESC 暂停 · 切至后台自动暂停 · {{selected.id==='blocks'?'单局 10 分钟':'分段同步，长时间游玩'}}</small></section></aside></div>
 </section>
</template>
<style scoped src="../css/arcade.css"></style>
