<script setup>
import {ref,watch,nextTick,onMounted,onUnmounted} from 'vue';
const props=defineProps({request:{type:Function,required:true},dialogHost:Function});
const catalog=ref({items:[],settings:{},open:false}),orders=ref({items:[],total:0}),offset=ref(0),tab=ref('goods'),busy=ref(false),error=ref(''),selected=ref(null),notice=ref('');
const modal=ref();let previousFocus;
watch(selected,async value=>{props.dialogHost?.(value?()=>{if(!busy.value)selected.value=null;}:null);if(value){previousFocus=document.activeElement;await nextTick();modal.value?.focus();}else previousFocus?.isConnected&&previousFocus.focus();});
function modalKey(event){if(event.key==='Escape'&&!busy.value){selected.value=null;event.preventDefault();}if(event.key==='Tab'){const controls=[...modal.value.querySelectorAll('button:not(:disabled)')];event.preventDefault();if(controls.length){const i=controls.indexOf(document.activeElement);controls[(i+(event.shiftKey?-1:1)+controls.length)%controls.length].focus();}}}
let requestId='',requestItem='',timer;
const date=t=>t?new Date(t).toLocaleString('zh-CN'):'不限';
async function load(){if(busy.value)return;busy.value=true;error.value='';try{if(tab.value==='goods')catalog.value=await props.request('/api/shop');else orders.value=await props.request('/api/shop/orders?offset='+offset.value);}catch(e){error.value=e.message;}finally{busy.value=false;}}
function pick(item){selected.value=item;if(requestItem!==item.id){requestId=crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(20)),n=>n.toString(16).padStart(2,'0')).join('');requestItem=item.id;}notice.value='';}
async function buy(){if(!selected.value||busy.value)return;busy.value=true;error.value='';try{await props.request('/api/shop/buy','POST',{item:selected.value.id,price:selected.value.price,requestId});selected.value=null;requestId='';requestItem='';notice.value='兑换成功，可在订单中查看交付状态。';tab.value='orders';offset.value=0;}catch(e){error.value=e.message;}finally{busy.value=false;}if(!error.value)await load();}
onMounted(()=>{void load();timer=setInterval(()=>{if(!document.hidden&&!selected.value)void load();},60000);});onUnmounted(()=>{clearInterval(timer);props.dialogHost?.(null);});
</script>
<template><section class="shop-page"><header class="shop-heading"><div><h1>积分商城</h1><p>{{catalog.open?'使用社区积分兑换商品':'商城暂未开放'}}<span v-if="catalog.settings.starts||catalog.settings.ends"> · {{date(catalog.settings.starts)}} — {{date(catalog.settings.ends)}}</span></p></div><button :disabled="busy" @click="load">刷新</button></header><nav class="shop-tabs"><button :class="{active:tab==='goods'}" @click="tab='goods';load()">商品</button><button :class="{active:tab==='orders'}" @click="tab='orders';load()">我的订单</button></nav><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<div v-if="tab==='goods'" class="shop-grid"><article v-for="item in catalog.items" :key="item.id" class="shop-product"><div class="shop-emblem">✦</div><h2>{{item.title}}</h2><p class="shop-description">{{item.description}}</p><small>库存：{{item.stock<0?'不限量':item.stock}}<br v-if="item.starts||item.ends"/><span v-if="item.starts||item.ends">{{date(item.starts)}} — {{date(item.ends)}}</span></small><footer><strong>{{item.price}} <small>积分</small></strong><button :disabled="!item.available||busy" @click="pick(item)">{{item.stock===0?'已售罄':item.available?'兑换':'未开放'}}</button></footer></article><p v-if="!catalog.items.length&&!busy">暂无上架商品</p></div>
<div v-else><article v-for="order in orders.items" :key="order.id" class="shop-order"><header><h2>{{order.title}}</h2><span>{{({pending:'待交付',fulfilled:'已交付',refunded:'已退款'})[order.status]}}</span></header><p>{{order.price}} 积分 · {{date(order.created)}}</p><p v-if="order.delivery" class="shop-description">{{order.delivery}}</p><small>订单 {{order.id}}</small></article><p v-if="!orders.items.length">暂无订单</p><div class="shop-pagination"><button :disabled="busy||!offset" @click="offset=Math.max(0,offset-30);load()">上一页</button><span>{{Math.floor(offset/30)+1}} / {{Math.max(1,Math.ceil(orders.total/30))}}</span><button :disabled="busy||offset+30>=orders.total" @click="offset+=30;load()">下一页</button></div></div>
<Teleport to="body"><div v-if="selected" class="shop-modal" @keydown="modalKey"><section ref="modal" role="dialog" aria-modal="true" aria-labelledby="shop-confirm-title" tabindex="-1"><h2 id="shop-confirm-title">确认兑换 {{selected.title}}？</h2><p class="shop-description">{{selected.description}}</p><p>将扣除 {{selected.price}} 积分，请确认商品说明及交付方式。</p><p v-if="error" role="alert">{{error}}</p><footer><button :disabled="busy" @click="selected=null">取消</button><button :disabled="busy" @click="buy">{{busy?'正在处理…':'确认兑换'}}</button></footer></section></div></Teleport></section></template>
<style scoped>.shop-page{color:var(--text);min-width:0}.shop-heading,.shop-order header{display:flex;align-items:center;justify-content:space-between;gap:16px}.shop-heading h1{font-size:1.55rem;margin:0}.shop-heading p,.shop-page small,.shop-order p{color:var(--muted);line-height:1.6}.shop-page button,.shop-modal button{font:inherit;color:inherit;background:var(--panel,var(--surface));border:1px solid var(--border,var(--line));border-radius:9px;padding:10px 16px;cursor:pointer}.shop-page button:disabled,.shop-modal button:disabled{opacity:.45;cursor:default}.shop-tabs{display:flex;gap:10px;margin:20px 0}.shop-tabs .active{background:var(--accent-soft,#91b67626)}.shop-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:18px}.shop-product,.shop-order{padding:22px;border:1px solid var(--border,var(--line));border-radius:16px;background:var(--panel,var(--surface));min-width:0}.shop-product{display:flex;flex-direction:column;gap:12px}.shop-product h2,.shop-order h2{margin:0;font-size:1.1rem;overflow-wrap:anywhere}.shop-emblem{display:grid;place-items:center;width:48px;height:48px;border-radius:15px;background:var(--accent-soft,#91b67626);font-size:28px;color:var(--accent)}.shop-description{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.75;flex:1;margin:0}.shop-product footer,.shop-pagination{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:12px}.shop-product footer strong{max-width:60%;overflow-wrap:anywhere}.shop-order{margin-bottom:14px}.shop-order>small{overflow-wrap:anywhere}.shop-modal{position:fixed;inset:0;z-index:9000;background:#071218cc;backdrop-filter:blur(8px);display:grid;place-items:center;padding:24px;color:var(--text)}.shop-modal section{width:min(440px,100%);max-height:85dvh;overflow:auto;padding:24px;border-radius:18px;background:var(--panel,var(--surface,#fff));box-shadow:0 24px 90px #0006}.shop-modal h2{font-size:1.2rem;overflow-wrap:anywhere}.shop-modal p{line-height:1.7;overflow-wrap:anywhere}.shop-modal footer{display:flex;justify-content:flex-end;gap:12px}</style>

<style scoped>
.shop-grid{align-items:stretch}.shop-product{position:relative;gap:14px;border-radius:12px;padding:20px}.shop-product>.shop-description{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;min-height:5.25em;flex:1}.shop-emblem{width:100%;height:88px;border-radius:8px;font-size:38px;background:linear-gradient(120deg,var(--accent-soft,#91b67626),transparent)}.shop-product footer{border-top:1px solid var(--border,var(--line));padding-top:16px}.shop-product footer button{background:var(--accent);color:var(--on-accent,#20321c);font-weight:600;white-space:nowrap}.shop-product footer strong{font-size:1.2em}.shop-product footer strong small{font-size:.75em}.shop-modal section{background:var(--panel,var(--surface,#fff));isolation:isolate}@media(max-width:520px){.shop-grid{grid-template-columns:minmax(0,1fr)}.shop-heading{align-items:flex-start}.shop-product>.shop-description{min-height:0}}
</style>
