import {useState,useEffect,useRef} from 'react';
import {useSnapshot} from 'valtio';
import {UserPlus,Globe,LogOut,RefreshCw,Coins,Camera,ArrowLeft} from 'lucide-react';
import {state,ui,invoke,reload,perform,saveSettings,account,notify} from './model';
import {community,communityRequest,connect,disconnect} from '../../../packages/community/client';
import {Button,Avatar,PageTitle,Select,Field,date,Empty} from './ui';
import {CardBoard,type CardSpec} from './CardBoard';
export function AccountPage(){
 const s=useSnapshot(state),u=useSnapshot(ui),c=useSnapshot(community),[skin,setSkin]=useState(false),[wallet,setWallet]=useState<any>(null),[error,setError]=useState(''),[code,setCode]=useState(''),[offset,setOffset]=useState(0);
 const box=useRef<HTMLDivElement>(null),selected=account(s),generation=useRef(0);
 async function loadWallet(){const id=++generation.current;try{const value=await communityRequest('/api/points?offset='+offset,{},true);if(id===generation.current){setWallet(value);setError('');}}catch(e:any){if(id===generation.current)setError(e.message);}}
 useEffect(()=>{setWallet(null);setError('');if(c.connected)void loadWallet();return()=>{generation.current++;};},[c.connected,c.user?.uid,offset]);
 useEffect(()=>{if(!skin||!box.current)return;let frame=0;const position=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const r=box.current?.getBoundingClientRect();if(r)void invoke('skin.bounds',{x:Math.round(r.x),y:Math.round(r.y),width:Math.round(r.width),height:Math.round(r.height)}).catch(()=>{});});};const observer=new ResizeObserver(position);observer.observe(box.current);window.addEventListener('resize',position);window.addEventListener('scroll',position,true);position();return()=>{observer.disconnect();window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);cancelAnimationFrame(frame);void invoke('skin.hide').catch(()=>{});};},[skin]);
 useEffect(()=>{if(u.dialog||u.tasks||u.confirm)setSkin(false);},[u.dialog,u.tasks,u.confirm]);
 if(skin)return <div className="standard-page"><PageTitle title="皮肤站账号管理" actions={<Button icon={ArrowLeft} onClick={()=>setSkin(false)}>返回账号</Button>}/><div ref={box} className="skin-surface"/></div>;
 const cards:CardSpec[]=[
 {id:'identity',title:'账号与角色',w:4,h:28,x:0,y:0,minW:4,minH:15,content:<section className="identity-card air-identity"><Avatar name={selected?.name} image={selected?.avatar} size={72}/><h2>{selected?.name||'你好，旅行者'}</h2><p>{selected?.username||'使用皮肤站账号登录游戏与社区'}</p>{selected?<><span className="status-label">{c.connected?'社区已连接':c.status}</span><Button icon={Camera} onClick={async()=>{const avatar=await invoke('avatar.choose');if(avatar){await invoke('avatar.save',{id:selected.id,avatar});await reload();}}}>更换头像</Button><Button icon={Globe} onClick={async()=>{await invoke('skin.open');setSkin(true);}}>打开皮肤站</Button></>:<Button tone="solid" onClick={()=>ui.dialog='account'}>登录账号</Button>}<div className="identity-accounts">{s.accounts.map((a:any)=><div key={a.id} className={selected?.id===a.id?'selected':''}><Avatar name={a.name} image={a.avatar}/><button onClick={()=>perform(async()=>{disconnect();await saveSettings({selectedAccount:a.id});void connect();})}><strong>{a.name||'选择游戏角色'}</strong><small>{a.username}</small></button><button className="quiet" title="移除此账号" onClick={()=>ui.confirm={title:'移除账号',message:'仅移除本机登录状态，不删除皮肤站账号。',action:async()=>{disconnect();await invoke('account.remove',{id:a.id});await reload();if(account())void connect();}}}><LogOut size={16}/></button></div>)}</div>{selected?.profiles?.length>1&&<Field label="游戏角色"><Select value={selected.uuid} options={selected.profiles.map((p:any)=>({value:p.id,label:p.name}))} onChange={(uuid:string)=>perform(async()=>{disconnect();await invoke('account.profile',{id:selected.id,uuid});await reload();void connect();})}/></Field>}</section>},
 {id:'wallet',title:'我的积分',x:4,y:0,w:8,h:10,minW:5,minH:9,content:<section className="wallet-panel"><div><span className="eyebrow">可用余额</span><h2>{wallet?.balance??'—'}<small>积分</small></h2></div><Coins size={46} strokeWidth={1.2}/><div className="wallet-actions"><input placeholder="输入积分兑换码" aria-label="积分兑换码" value={code} onChange={e=>setCode(e.target.value)}/><Button tone="solid" disabled={!code.trim()||!c.connected} onClick={async()=>{await communityRequest('/api/points/redeem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:code.trim()})},true);setCode('');await loadWallet();notify('兑换成功');}}>兑换</Button></div></section>},
 {id:'ledger',title:'收支记录',x:4,y:10,w:8,h:18,minW:5,minH:12,content:<><div className="ledger-heading"><small>消费不会扣除已经获得的榜单积分</small><Button icon={RefreshCw} disabled={!c.connected} onClick={loadWallet}>刷新</Button></div>{error&&<p className="inline-error">{error}</p>}{wallet?.ledger?.length?<><div className="transaction-list">{wallet.ledger.map((entry:any)=><div key={entry.id}><span><strong>{entry.reason}</strong><small>{date(entry.created)}</small></span><b className={String(entry.amount).startsWith('-')?'':'positive'}>{String(entry.amount).startsWith('-')?'':'+'}{entry.amount}</b></div>)}</div><div className="pagination"><Button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-30))}>上一页</Button><span>{Math.floor(offset/30)+1}</span><Button disabled={offset+30>=wallet.total} onClick={()=>setOffset(offset+30)}>下一页</Button></div></>:<Empty icon={Coins} title={c.connected?'暂无收支记录':'连接社区后查看积分'}/>}</>}
 ];
 return <div className="standard-page"><PageTitle title="账号管理" actions={<Button icon={UserPlus} onClick={()=>ui.dialog='account'}>添加账号</Button>}/><CardBoard id="account" cards={cards}/></div>;
}
