import {useEffect,useState} from 'react';
import {useSnapshot} from 'valtio';
import {useNavigate} from 'react-router-dom';
import {Mail,CheckCheck,Send,RefreshCw} from 'lucide-react';
import {community} from '../../../packages/community/client';
import {CardBoard} from './CardBoard';
import {Button,IconButton,Modal,Field,Select,Empty,date} from './ui';
import {request,useData} from './data';
import {perform,notify} from './model';

export function useInboxCount(){const c=useSnapshot(community),[count,setCount]=useState(0);useEffect(()=>{let active=true;const load=()=>{if(c.connected)void request('/api/inbox/unread').then(v=>active&&setCount(v.unread)).catch(()=>{});else setCount(0);};load();window.addEventListener('hxz-inbox',load);return()=>{active=false;window.removeEventListener('hxz-inbox',load);};},[c.connected,c.user?.uid]);return count;}
export function InboxButton(){const n=useInboxCount(),navigate=useNavigate();return <button className="inbox-indicator" title={'收件箱'+(n?' · '+n+' 条未读':'')} aria-label={'收件箱'+(n?'，'+n+' 条未读':'')} onClick={()=>navigate('/community/inbox')}><Mail size={19}/>{n>0&&<b>{n>99?'99+':n}</b>}</button>;}
export function InboxPage(){
 const c=useSnapshot(community),navigate=useNavigate(),[filter,setFilter]=useState('all'),[before,setBefore]=useState<number[]>([]),[sending,setSending]=useState(false),[form,setForm]=useState({title:'',body:'',recipients:'',all:false});
 const list=useData(()=>c.connected?request('/api/inbox?unread='+(filter==='unread'?1:0)+(before.length?'&before='+before.at(-1):'')):Promise.resolve({items:[],unread:0,more:false}),[c.connected,c.user?.uid,filter,before.at(-1)]);
 useEffect(()=>{const fn=()=>void list.reload();window.addEventListener('hxz-inbox',fn);return()=>window.removeEventListener('hxz-inbox',fn);},[list.reload]);
 async function read(item:any){await request('/api/inbox/read','POST',{id:item.id});window.dispatchEvent(new Event('hxz-inbox'));if(item.target&&/^\/(?:community|workshop|account)(?:[/?]|$)/.test(item.target))navigate(item.target);}
 return <div className="inbox-page"><CardBoard id="inbox" cards={[{id:'messages',title:'我的收件箱',w:12,minW:5,content:<><div className="list-toolbar"><Select label="消息范围" value={filter} onChange={(v:string)=>{setFilter(v);setBefore([]);}} options={[{value:'all',label:'全部消息'},{value:'unread',label:'仅未读'}]}/><span className="muted">{list.data?.unread||0} 条未读</span><Button icon={CheckCheck} disabled={!c.connected||!list.data?.unread} onClick={async()=>{await request('/api/inbox/read','POST',{all:true});window.dispatchEvent(new Event('hxz-inbox'));}}>全部已读</Button><IconButton icon={RefreshCw} label="刷新收件箱" onClick={list.reload}/>{c.user?.admin&&<Button icon={Send} onClick={()=>setSending(true)}>发送站内信</Button>}</div>{list.error&&<p className="inline-error">{list.error}</p>}<div className="inbox-list">{list.data?.items.map((v:any)=><button key={v.id} className={'inbox-message '+(!v.readAt?'unread':'')} onClick={()=>void perform(()=>read(v))}><span className="inbox-dot"/><div><header><strong>{v.title}</strong><time>{date(v.created)}</time></header><p>{v.body}</p><small>{v.target?'查看内容':'站内消息'}</small></div></button>)}</div>{!list.loading&&!list.data?.items.length&&<Empty icon={Mail} title={c.connected?'收件箱已经看完了':'连接社区后查看收件箱'}/>}<div className="pagination"><Button disabled={!before.length} onClick={()=>setBefore(v=>v.slice(0,-1))}>上一页</Button><span>第 {before.length+1} 页</span><Button disabled={!list.data?.more} onClick={()=>setBefore(v=>[...v,list.data.items.at(-1).id])}>下一页</Button></div></>}]} /><Modal open={sending} title="发送站内信" onClose={()=>setSending(false)}><Field label="标题"><input value={form.title} maxLength={100} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="正文"><textarea rows={5} maxLength={2000} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></Field><Field label="接收范围"><Select value={form.all?'all':'selected'} onChange={(v:string)=>setForm({...form,all:v==='all'})} options={[{value:'selected',label:'指定成员'},{value:'all',label:'全体成员'}]}/></Field>{!form.all&&<Field label="收件人 UUID" hint="多位成员每行一个，可在社区管理后台查看。"><textarea rows={3} value={form.recipients} onChange={e=>setForm({...form,recipients:e.target.value})}/></Field>}<footer className="modal-actions"><Button onClick={()=>setSending(false)}>取消</Button><Button tone="solid" disabled={!form.title.trim()||!form.body.trim()||!form.all&&!form.recipients.trim()} onClick={async()=>{await request('/api/admin/inbox/send','POST',{...form,id:crypto.randomUUID(),recipients:form.recipients.trim().split(/\s+/)});setSending(false);setForm({title:'',body:'',recipients:'',all:false});notify('站内信已发送');}}>发送</Button></footer></Modal></div>;
}
