import {useEffect,useLayoutEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {useSnapshot} from 'valtio';
import {useLocation} from 'react-router-dom';
import {AlignLeft,Minimize2,Pin,RefreshCw,UserRound,LogOut,GripVertical,ArrowUp,ArrowDown} from 'lucide-react';
import {music,seekMusic,stopMusic} from './music-player';
import {Button,IconButton,Modal,Empty} from './ui';
import {useData} from './data';
import {invoke,state,perform} from './model';
import {community} from '../../../packages/community/client';

export async function loadLyrics(){const id=music.current?.id;if(!id)return;music.lyrics=[];music.lyricError='';music.lyricCandidates=[];music.lyricLoading=true;try{const r=await invoke('music.lyrics',{id});if(music.current?.id===id){music.lyrics=r.lines;music.lyricCandidates=r.candidates||[];}}catch(e:any){if(music.current?.id===id)music.lyricError=e.message;}finally{if(music.current?.id===id)music.lyricLoading=false;}}
export function LyricsHost(){const m=useSnapshot(music),c=useSnapshot(community),s=useSnapshot(state);useEffect(()=>{void loadLyrics();},[m.current?.id]);useEffect(()=>{const changed=()=>{if(music.current?.privateAudio)stopMusic();};window.addEventListener('hxz-music-access',changed);return()=>window.removeEventListener('hxz-music-access',changed);},[]);useEffect(()=>{if(music.current?.privateAudio)stopMusic();},[s.settings.selectedAccount,s.settings.communityUrl,c.user?.uid]);return null;}
export function LyricsCard(){const m=useSnapshot(music),s=useSnapshot(state),box=useRef<HTMLDivElement>(null);const index=m.lyrics?.findLastIndex((r:any)=>r.time<=m.position)??-1;useEffect(()=>{const el=box.current,node=el?.querySelector<HTMLElement>('[aria-current=true]');if(el&&node)el.scrollTo({top:node.offsetTop-el.offsetTop-el.clientHeight/2+node.clientHeight/2,behavior:s.settings.animationSpeed===0||matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[index]);return <div className="lyrics-card"><div className="actions"><Button icon={Pin} onClick={()=>music.lyricsFloating=!m.lyricsFloating}>{m.lyricsFloating?'收回悬浮歌词':'其他页面也显示'}</Button><IconButton icon={RefreshCw} label="重新获取歌词" disabled={!m.current||m.lyricLoading} onClick={loadLyrics}/></div><div ref={box} className="lyrics-scroll">{m.lyrics?.map((line:any,i:number)=><button key={i} aria-current={i===index} className={i===index?'current':''} onClick={()=>seekMusic(line.time)}><span>{line.text}</span>{line.translation&&<small>{line.translation}</small>}</button>)}{!m.lyrics?.length&&<Empty icon={AlignLeft} title={m.lyricLoading?'正在获取歌词':m.lyricError||(!m.current?'选择音乐后显示歌词':'暂无同步歌词')}/>}</div>{!!m.lyricCandidates?.length&&<div className="lyric-candidates"><p className="muted">为本地音乐选择对应歌词</p>{m.lyricCandidates.map((t:any)=><Button key={t.id} onClick={async()=>{const id=music.current?.id;const r=await invoke('music.lyrics.bind',{id,netId:t.netId});if(music.current?.id===id){music.lyrics=r.lines;music.lyricCandidates=[];}}}>{t.title} · {t.artist}</Button>)}</div>}</div>;}
type LyricsPosition={edge:'top'|'bottom';x:number};
function readLyricsPosition():LyricsPosition{try{const value=JSON.parse(localStorage.getItem('hxz-lyrics-position')||'{}');return {edge:value.edge==='top'?'top':'bottom',x:Number.isFinite(value.x)?Math.max(0,Math.min(1,value.x)):0};}catch{return {edge:'bottom',x:0};}}
export function FloatingLyrics(){
 const m=useSnapshot(music),location=useLocation(),[position,setPosition]=useState(readLyricsPosition),[preview,setPreview]=useState<{left:number;top:number;width:number}|null>(null),dock=useRef<HTMLDivElement>(null),panel=useRef<HTMLElement>(null),drag=useRef<{id:number;dx:number;dy:number;width:number;height:number}|null>(null);
 const visible=!!m.lyricsFloating&&!!m.current&&location.pathname!=='/music';
 useLayoutEffect(()=>{const shell=document.querySelector<HTMLElement>('.air-shell');if(!shell)return;shell.dataset.lyricsDock=visible?position.edge:'';return()=>{delete shell.dataset.lyricsDock;};},[visible,position.edge]);
 useEffect(()=>{try{localStorage.setItem('hxz-lyrics-position',JSON.stringify(position));}catch{}},[position]);
 useEffect(()=>{drag.current=null;setPreview(null);},[visible,location.pathname]);
 function begin(e:ReactPointerEvent<HTMLButtonElement>){if(e.button!==0)return;const r=panel.current?.getBoundingClientRect();if(!r)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:e.pointerId,dx:e.clientX-r.left,dy:e.clientY-r.top,width:r.width,height:r.height};setPreview({left:r.left,top:r.top,width:r.width});}
 function move(e:ReactPointerEvent<HTMLButtonElement>){const d=drag.current;if(!d||d.id!==e.pointerId)return;setPreview({left:Math.max(8,Math.min(innerWidth-d.width-8,e.clientX-d.dx)),top:Math.max(76,Math.min(innerHeight-d.height-34,e.clientY-d.dy)),width:d.width});}
 function end(e:ReactPointerEvent<HTMLButtonElement>){const d=drag.current;if(!d||d.id!==e.pointerId)return;const bounds=dock.current?.getBoundingClientRect(),width=bounds?.width||innerWidth,space=Math.max(0,width-36-d.width),left=Math.max(0,Math.min(space,e.clientX-d.dx-(bounds?.left||0)-18));drag.current=null;setPreview(null);setPosition({edge:e.clientY<innerHeight/2?'top':'bottom',x:space?left/space:0});if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
 if(!visible)return null;const i=m.lyrics?.findLastIndex((r:any)=>r.time<=m.position)??-1,line=m.lyrics?.[Math.max(0,i)],text=line?.text||(m.lyricLoading?'正在获取歌词':m.lyricError||'暂无同步歌词');
 return <div ref={dock} className={'lyrics-dock '+(preview?'is-dragging':'')} data-edge={position.edge}><aside ref={panel} className="floating-lyrics" aria-label="悬浮歌词" style={preview?{position:'fixed',left:preview.left,top:preview.top,width:preview.width}:{marginLeft:`calc((100% - min(720px,100%)) * ${position.x})`}}><button className="lyrics-drag-handle" title="拖动歌词 · 松手贴靠顶部或底部" aria-label="拖动歌词位置" onPointerDown={begin} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{drag.current=null;setPreview(null);}} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();setPosition(v=>({...v,edge:e.key==='ArrowUp'?'top':'bottom'}));}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setPosition(v=>({...v,x:Math.max(0,Math.min(1,v.x+(e.key==='ArrowRight'?.1:-.1)))}));}}}><GripVertical size={17}/></button><div className="floating-lyrics-lines"><small title={m.current.title}>{m.current.title}</small><strong title={text}>{text}</strong>{line?.translation&&<span title={line.translation}>{line.translation}</span>}</div><IconButton icon={position.edge==='top'?ArrowDown:ArrowUp} label={position.edge==='top'?'歌词贴靠底部':'歌词贴靠顶部'} onClick={()=>setPosition(v=>({...v,edge:v.edge==='top'?'bottom':'top'}))}/><IconButton icon={Minimize2} label="收回歌词到音乐控件" onClick={()=>music.lyricsFloating=false}/></aside></div>;
}
export function NeteaseAccount(){const c=useSnapshot(community),[consent,setConsent]=useState(false),status=useData(()=>c.connected?invoke('music.account.status'):Promise.resolve({allowed:false,loggedIn:false}),[c.connected,c.user?.uid]);useEffect(()=>{const fn=()=>void status.reload();window.addEventListener('focus',fn);window.addEventListener('hxz-music-access',fn);return()=>{window.removeEventListener('focus',fn);window.removeEventListener('hxz-music-access',fn);};},[status.reload]);return <><div className="netease-account"><UserRound size={19}/><div><strong>{status.data?.loggedIn?'个人网易云账号已登录':'使用自己的网易云账号'}</strong><small>{status.error||(!c.connected?'请先连接社区':status.data?.allowed?'仅在本机保存登录状态':'此功能需由社区管理员授权')}</small></div>{status.data?.loggedIn?<Button icon={LogOut} onClick={async()=>{if(music.current?.privateAudio)stopMusic();await invoke('music.account.logout');await status.reload();}}>退出</Button>:<Button disabled={!status.data?.allowed} onClick={()=>setConsent(true)}>登录</Button>}<IconButton icon={RefreshCw} label="刷新网易云登录状态" onClick={status.reload}/></div><Modal open={consent} title="登录个人网易云账号" onClose={()=>setConsent(false)}><div className="consent-copy"><p>接下来打开网易云官方登录页面。请只登录你自己的账号。</p><p>登录状态保存在此设备的独立会话中，不会传给社区管理员或其他玩家。在公用电脑上使用后，请点击“退出”清除登录状态。</p><p>第三方播放器可能触发验证码、异地登录或账号风控。可播放内容由网易云根据你的账号、会员和版权权限决定，授权名单不会提供额外的曲目权限。</p></div><footer className="modal-actions"><Button onClick={()=>setConsent(false)}>取消</Button><Button tone="solid" onClick={async()=>{await invoke('music.account.login',{accepted:true});setConsent(false);await status.reload();}}>同意并打开官方登录</Button></footer></Modal></>;}
