import {useEffect,useRef,useState} from 'react';
import {useSnapshot} from 'valtio';
import {useLocation} from 'react-router-dom';
import {AlignLeft,Minimize2,Pin,RefreshCw,UserRound,LogOut} from 'lucide-react';
import {music,seekMusic,stopMusic} from './music-player';
import {Button,IconButton,Modal,Empty} from './ui';
import {useData} from './data';
import {invoke,state,perform} from './model';
import {community} from '../../../packages/community/client';

export async function loadLyrics(){const id=music.current?.id;if(!id)return;music.lyrics=[];music.lyricError='';music.lyricCandidates=[];music.lyricLoading=true;try{const r=await invoke('music.lyrics',{id});if(music.current?.id===id){music.lyrics=r.lines;music.lyricCandidates=r.candidates||[];}}catch(e:any){if(music.current?.id===id)music.lyricError=e.message;}finally{if(music.current?.id===id)music.lyricLoading=false;}}
export function LyricsHost(){const m=useSnapshot(music),c=useSnapshot(community),s=useSnapshot(state);useEffect(()=>{void loadLyrics();},[m.current?.id]);useEffect(()=>{const changed=()=>{if(music.current?.privateAudio)stopMusic();};window.addEventListener('hxz-music-access',changed);return()=>window.removeEventListener('hxz-music-access',changed);},[]);useEffect(()=>{if(music.current?.privateAudio)stopMusic();},[s.settings.selectedAccount,s.settings.communityUrl,c.user?.uid]);return null;}
export function LyricsCard(){const m=useSnapshot(music),s=useSnapshot(state),box=useRef<HTMLDivElement>(null);const index=m.lyrics?.findLastIndex((r:any)=>r.time<=m.position)??-1;useEffect(()=>{const el=box.current,node=el?.querySelector<HTMLElement>('[aria-current=true]');if(el&&node)el.scrollTo({top:node.offsetTop-el.offsetTop-el.clientHeight/2+node.clientHeight/2,behavior:s.settings.animationSpeed===0||matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[index]);return <div className="lyrics-card"><div className="actions"><Button icon={Pin} onClick={()=>music.lyricsFloating=!m.lyricsFloating}>{m.lyricsFloating?'收回悬浮歌词':'其他页面也显示'}</Button><IconButton icon={RefreshCw} label="重新获取歌词" disabled={!m.current||m.lyricLoading} onClick={loadLyrics}/></div><div ref={box} className="lyrics-scroll">{m.lyrics?.map((line:any,i:number)=><button key={i} aria-current={i===index} className={i===index?'current':''} onClick={()=>seekMusic(line.time)}><span>{line.text}</span>{line.translation&&<small>{line.translation}</small>}</button>)}{!m.lyrics?.length&&<Empty icon={AlignLeft} title={m.lyricLoading?'正在获取歌词':m.lyricError||(!m.current?'选择音乐后显示歌词':'暂无同步歌词')}/>}</div>{!!m.lyricCandidates?.length&&<div className="lyric-candidates"><p className="muted">为本地音乐选择对应歌词</p>{m.lyricCandidates.map((t:any)=><Button key={t.id} onClick={async()=>{const id=music.current?.id;const r=await invoke('music.lyrics.bind',{id,netId:t.netId});if(music.current?.id===id){music.lyrics=r.lines;music.lyricCandidates=[];}}}>{t.title} · {t.artist}</Button>)}</div>}</div>;}
export function FloatingLyrics(){const m=useSnapshot(music),location=useLocation();if(!m.lyricsFloating||!m.current||location.pathname==='/music')return null;const i=m.lyrics?.findLastIndex((r:any)=>r.time<=m.position)??-1,line=m.lyrics?.[Math.max(0,i)];return <aside className="floating-lyrics" aria-label="悬浮歌词"><div><small>{m.current.title}</small><strong>{line?.text||(m.lyricLoading?'正在获取歌词':m.lyricError||'暂无同步歌词')}</strong>{line?.translation&&<span>{line.translation}</span>}</div><IconButton icon={Minimize2} label="收回歌词到音乐控件" onClick={()=>music.lyricsFloating=false}/></aside>;}
export function NeteaseAccount(){const c=useSnapshot(community),[consent,setConsent]=useState(false),status=useData(()=>c.connected?invoke('music.account.status'):Promise.resolve({allowed:false,loggedIn:false}),[c.connected,c.user?.uid]);useEffect(()=>{const fn=()=>void status.reload();window.addEventListener('focus',fn);window.addEventListener('hxz-music-access',fn);return()=>{window.removeEventListener('focus',fn);window.removeEventListener('hxz-music-access',fn);};},[status.reload]);return <><div className="netease-account"><UserRound size={19}/><div><strong>{status.data?.loggedIn?'个人网易云账号已登录':'使用自己的网易云账号'}</strong><small>{status.error||(!c.connected?'请先连接社区':status.data?.allowed?'仅在本机保存登录状态':'此功能需由社区管理员授权')}</small></div>{status.data?.loggedIn?<Button icon={LogOut} onClick={async()=>{if(music.current?.privateAudio)stopMusic();await invoke('music.account.logout');await status.reload();}}>退出</Button>:<Button disabled={!status.data?.allowed} onClick={()=>setConsent(true)}>登录</Button>}<IconButton icon={RefreshCw} label="刷新网易云登录状态" onClick={status.reload}/></div><Modal open={consent} title="登录个人网易云账号" onClose={()=>setConsent(false)}><div className="consent-copy"><p>接下来打开网易云官方登录页面。请只登录你自己的账号。</p><p>登录状态保存在此设备的独立会话中，不会传给社区管理员或其他玩家。在公用电脑上使用后，请点击“退出”清除登录状态。</p><p>第三方播放器可能触发验证码、异地登录或账号风控。可播放内容由网易云根据你的账号、会员和版权权限决定，授权名单不会提供额外的曲目权限。</p></div><footer className="modal-actions"><Button onClick={()=>setConsent(false)}>取消</Button><Button tone="solid" onClick={async()=>{await invoke('music.account.login',{accepted:true});setConsent(false);await status.reload();}}>同意并打开官方登录</Button></footer></Modal></>;}
