import {ServerOnline} from './ServerOnline';
import {useEffect,useState} from 'react';
import {useSnapshot} from 'valtio';
import {Link} from 'react-router-dom';
import {Network,ShieldCheck,Plus,LogIn,Copy,RefreshCw,Play,Unplug,CheckCircle2,AlertCircle,Globe,Users} from 'lucide-react';
import {CardBoard,type CardSpec} from './CardBoard';
import {CardActions,CardCollection,ContentCard} from './CardPrimitives';
import {Button,Field,Select,Empty,Modal,Toggle} from './ui';
import {state,ui,invoke,notify,bytes} from './model';

export function MultiplayerPage(){
 const s=useSnapshot(state),instances=s.instances.filter((v:any)=>v.installed);
 const [status,setStatus]=useState<any>({mode:'idle',phase:'尚未连接',checks:[]}),[access,setAccess]=useState<any>(null),[accessError,setAccessError]=useState('');
 const [name,setName]=useState('一起玩 Minecraft'),[instance,setInstance]=useState(''),[scope,setScope]=useState('internet'),[invite,setInvite]=useState(''),[checked,setChecked]=useState<any>(null),[grants,setGrants]=useState<any>({items:[],members:[]}),[member,setMember]=useState(''),[closing,setClosing]=useState(false),[adapters,setAdapters]=useState<any[]>([]),[adapter,setAdapter]=useState(''),[allowRelay,setAllowRelay]=useState(true);
 const [publicRoom,setPublicRoom]=useState(true),[rooms,setRooms]=useState<any[]>([]),[roomsError,setRoomsError]=useState(''),[roomsLoading,setRoomsLoading]=useState(false);
 const chosen=instances.some((v:any)=>v.id===instance)?instance:instances[0]?.id||'';
 const active=status.mode!=='idle',running=s.running,busy=active||running;
 async function permissions(){if(!s.settings.selectedAccount){ui.dialog='account';return;}setAccessError('');try{const result=await invoke('lobby.access');setAccess(result);if(result.admin)setGrants(await invoke('lobby.grants'));}catch(e:any){setAccess(null);setAccessError(e.message);}}
 async function refresh(){setStatus(await invoke('lobby.status'));}
 async function refreshRooms(){if(!s.settings.selectedAccount){setRooms([]);setRoomsError('');return;}setRoomsLoading(true);try{const value=await invoke('lobby.rooms');setRooms(value.items);setRoomsError('');}catch(e:any){setRoomsError(e.message);}finally{setRoomsLoading(false);}}
 useEffect(()=>{void invoke('lobby.adapters').then(setAdapters).catch(()=>{});},[]);
 useEffect(()=>{void refreshRooms();const timer=setInterval(()=>void refreshRooms(),20000);return()=>clearInterval(timer);},[s.settings.selectedAccount]);
 useEffect(()=>{let mounted=true;const read=()=>invoke('lobby.status').then(v=>{if(mounted)setStatus(v);}).catch(()=>{});void read();const stop=window.launcher?.subscribe(e=>{if(e.type==='lobby'&&mounted)setStatus(e.value);});const timer=setInterval(read,2000);return()=>{mounted=false;stop?.();clearInterval(timer);};},[]);
 useEffect(()=>{if(s.settings.selectedAccount)void permissions();else setAccess(null);},[s.settings.selectedAccount]);
 async function start(mode:'host'|'guest',invitation=invite){
  if(!chosen)throw Error('请先安装或导入一个游戏实例');
  if(!s.settings.selectedAccount){ui.dialog='account';return;}
  try{
   const result=await invoke(mode==='host'?'lobby.host':'lobby.join',mode==='host'?{name,instance:chosen,scope,adapter,allowRelay,public:publicRoom}:{invite:invitation,instance:chosen});setStatus(result);void refreshRooms();
   ui.tasks=true;await invoke('lobby.launch',{instance:chosen});
  }catch(error){await refresh();throw error;}
 }
 const selector=<Field label="游戏实例" hint="所有玩家需使用相同游戏版本、加载器及模组。"><Select label="联机游戏实例" value={chosen} disabled={busy} onChange={setInstance} options={instances.length?instances.map((v:any)=>({value:v.id,label:`${v.name||v.id} · ${v.version||''}`})):[{value:'',label:'没有已安装的实例'}]}/></Field>;
 const cards:CardSpec[]=[
 {id:'default-online',title:'默认服务器 · 在线玩家',w:12,y:50,minW:5,content:<ServerOnline/>},
  {id:'session',title:'当前联机',w:12,minW:5,content:<div className="lobby-session"><div className="lobby-session-title"><span className="lobby-symbol"><Network size={27}/></span><div><h2>{status.room?.name||status.guest?.name||'和伙伴进入同一个世界'}</h2><p role="status">{status.phase}</p></div></div><div className="lobby-metrics">{active&&<span>{status.transport==='relay'?'社区限速中继':status.transport==='virtual'?'虚拟局域网直连':'房主直连'}{status.relayConnected?' · 中继可用 '+status.relayLimit+' KB/s':''}</span>}<span><ShieldCheck size={16}/>{status.mode==='host'?'房主':status.mode==='guest'?'已加入':'邀请制联机'}</span><span><Users size={16}/>{status.connections||0} 条游戏连接</span>{status.mode==='host'&&<span>接收 {bytes(status.bytesIn||0)} · 发送 {bytes(status.bytesOut||0)}</span>}</div>{status.error&&<p className="inline-error">{status.error}</p>}{status.directoryError&&<p className="muted">{status.directoryError}</p>}{active&&<CardActions><Button icon={Unplug} onClick={()=>setClosing(true)}>关闭当前联机</Button>{status.room?.invite&&<Button icon={Copy} onClick={async()=>{await navigator.clipboard.writeText(status.room.invite);notify('已复制房间邀请，请私发给伙伴');}}>复制邀请</Button>}{status.mode==='host'&&!running&&<Button tone="solid" icon={Play} onClick={async()=>{ui.tasks=true;await invoke('lobby.launch',{instance:status.room.instance});}}>启动房主游戏</Button>}{status.mode==='guest'&&!running&&<Button tone="solid" icon={Play} onClick={async()=>{ui.tasks=true;await invoke('lobby.launch',{instance:status.guest.instance});}}>启动并加入</Button>}</CardActions>}{status.room&&<p className="muted">进入单人世界后会自动开放。退出游戏或关闭房间将断开联机。邀请仅在本次房间有效。公开房间中的社区玩家可直接加入。</p>}</div>},
  {id:'host',title:'创建房间',w:6,x:0,y:24,minW:4,content:<div className="lobby-form">{access?.canHost?<><Field label="房间名称"><input value={name} maxLength={80} disabled={busy} onChange={e=>setName(e.target.value)}/></Field>{selector}<Field label="连接范围"><Select value={scope} onChange={setScope} disabled={busy} options={[{value:'internet',label:'异地联机 · 自动检测公网'},{value:'lan',label:'同一局域网'},{value:'virtual',label:'已有虚拟局域网'}]}/></Field>{scope==='virtual'&&<Field label="虚拟网络适配器" hint="请先在房主与伙伴电脑上加入同一个虚拟局域网，再选择对应地址。"><Select value={adapter} onChange={setAdapter} disabled={busy} options={[{value:'',label:'选择虚拟网络地址'},...adapters.map(v=>({value:v.address,label:v.name+' · '+v.address}))]}/></Field>}{scope!=='lan'&&<Toggle label="直连失败时使用社区中继" description="默认每房间 256 KB/s；限速由管理员调整。" checked={allowRelay} disabled={busy} onChange={setAllowRelay}/>}<Toggle label="在大厅公开房间" description="关闭后仅通过邀请加入" checked={publicRoom} disabled={busy} onChange={setPublicRoom}/><Button tone="solid" icon={Plus} disabled={busy||!chosen||!name.trim()} onClick={()=>start('host')}>检测网络并启动房间</Button></>:<><div className="lobby-permission"><ShieldCheck size={26}/><div><strong>{access?'需要管理员授权开房':'验证社区开房权限'}</strong><p>{access?'普通玩家可从公开房间或通过邀请加入，开房资格由社区管理员授权。':'使用皮肤站角色登录后验证开房权限。'}</p></div></div>{accessError&&<p className="inline-error">{accessError}</p>}<Button icon={RefreshCw} onClick={permissions}>{s.settings.selectedAccount?'刷新开房权限':'登录角色'}</Button></>}</div>},
  {id:'join',title:'加入伙伴',w:6,x:6,y:24,minW:4,content:<div className="lobby-form"><Field label="房间邀请"><textarea value={invite} rows={3} disabled={busy} placeholder="粘贴房主发来的 hxz-room:// 邀请" onChange={e=>{setInvite(e.target.value);setChecked(null);}}/></Field>{selector}<CardActions><Button icon={Network} disabled={!invite.trim()||busy} onClick={async()=>setChecked(await invoke('lobby.inspect',{invite}))}>检测连接</Button><Button tone="solid" icon={LogIn} disabled={!invite.trim()||!chosen||busy} onClick={()=>start('guest')}>启动并加入</Button></CardActions>{checked&&<p className={checked.ready?'lobby-success':'muted'}>{checked.name} · {checked.latency} ms · {checked.ready?'世界已开放，可以加入':'网络可达，等待房主进入世界'}</p>}</div>},
  {id:'network',title:'连接检查',w:6,x:0,y:26,minW:4,content:status.checks?.length?<div className="lobby-checks">{status.checks.map((item:any,i:number)=><div key={i}>{item.ok?<CheckCircle2 size={19}/>:<AlertCircle size={19}/>}<span><strong>{item.label}</strong><small>{item.detail}</small></span></div>)}</div>:<Empty icon={Globe} title="先检测，再启动">创建前检查开房权限和网络连通性；加入前检查房主是否在线、世界是否就绪。</Empty>},
  {id:'guide',title:'如何一起玩',w:6,x:6,y:26,minW:4,content:<ol className="lobby-guide"><li><strong>房主创建</strong><span>选择实例，检测通过后启动游戏，再进入自己的单人世界。</span></li><li><strong>分享邀请</strong><span>世界自动开放后，将房间邀请私发给伙伴。</span></li><li><strong>伙伴加入</strong><span>粘贴邀请，选择相同整合包，点击“启动并加入”。</span></li></ol>},
 ];
 cards.splice(1,0,{id:'rooms',title:'正在联机的房间',w:12,y:10,minW:5,content:<div className="lobby-form"><CardActions><span className="muted">{rooms.length} 个公开房间 · 每 20 秒刷新</span><Button icon={RefreshCw} disabled={roomsLoading} onClick={refreshRooms}>{roomsLoading?'读取中…':'刷新房间'}</Button></CardActions>{roomsError?<p className="inline-error">{roomsError}</p>:!s.settings.selectedAccount?<Empty icon={Users} title="登录后查看社区房间" action={<Button onClick={()=>ui.dialog='account'}>登录角色</Button>}>已有邀请仍可直接检测房主连接。</Empty>:rooms.length?<><Field label="用于加入的游戏实例"><Select value={chosen} onChange={setInstance} disabled={busy} options={instances.map((v:any)=>({value:v.id,label:v.name||v.id}))}/></Field><CardCollection className="lobby-room-list" minWidth={300}>{rooms.map((item:any)=><ContentCard key={item.id} title={item.name} footer={<Button icon={LogIn} tone="solid" disabled={busy||!chosen||!item.ready} onClick={()=>start('guest',item.invite)}>{item.ready?'启动并加入':'等待房主进入世界'}</Button>}><p>{item.owner} · {item.version||'版本待确认'} {item.loader||''}</p><p>{item.scope==='lan'?'同一局域网':item.scope==='virtual'?'虚拟局域网':'直连优先 · 支持中继'} · {item.connections||0} 条连接</p><span className={item.ready?'lobby-success':'muted'}>{item.ready?'世界已开放':'世界准备中'}</span></ContentCard>)}</CardCollection></>:<Empty icon={Users} title="暂时没有公开房间">授权房主开房后会显示在这里，也可以使用伙伴私发的邀请。</Empty>}</div>});
 if(access?.admin)cards.push({id:'permissions',title:'管理员 · 房主授权',w:12,y:40,minW:5,content:<div className="lobby-form"><CardActions><div className="lobby-member-picker"><Select label="授权社区成员" value={member} onChange={setMember} options={[{value:'',label:'选择已登录过社区的成员'},...grants.members.map((v:any)=>({value:v.uid,label:v.name+' · '+v.uid.slice(0,8)}))]}/></div><Button disabled={!member} onClick={async()=>{await invoke('lobby.grant',{uid:member,enabled:true});setGrants(await invoke('lobby.grants'));}}>允许创建房间</Button><Button icon={RefreshCw} onClick={()=>invoke('lobby.grants').then(setGrants)}>刷新</Button></CardActions><div className="lobby-grants">{grants.items.length?grants.items.map((v:any)=><div key={v.uid}><span><strong>{v.name}</strong><small>{v.uid}</small></span><Button onClick={async()=>{await invoke('lobby.grant',{uid:v.uid,enabled:false});setGrants(await invoke('lobby.grants'));}}>撤销</Button></div>):<p className="muted">尚未授权普通成员，社区管理员自身可以开房。</p>}</div></div>});
 return <div className="standard-page multiplayer-page"><div className="workspace-top"><div><h1>MC 联机大厅</h1><p className="muted">直连优先 · 虚拟局域网与限速中继 · 世界留在房主电脑</p></div><Button icon={RefreshCw} onClick={async()=>{await refresh();await permissions();await refreshRooms();}}>刷新状态</Button></div>{!instances.length&&<p className="lobby-banner">需要先安装游戏。<Link to="/workshop">前往下载与安装</Link></p>}<CardBoard id="multiplayer" label="联机卡片" cards={cards}/><Modal open={closing} onClose={()=>setClosing(false)} title="关闭当前联机？"><p>房间中的连接会断开，游戏世界及存档会保留。</p><footer className="modal-actions"><Button onClick={()=>setClosing(false)}>继续联机</Button><Button tone="solid" onClick={async()=>{await invoke('lobby.close');setClosing(false);await refresh();}}>关闭联机</Button></footer></Modal></div>;
}
