import {LyricsCard,LyricsHost,NeteaseAccount} from './Lyrics';
import {useEffect,useRef,useState} from 'react';
import {useSnapshot} from 'valtio';
import {Link} from 'react-router-dom';
import {Music2,Play,Pause,SkipBack,SkipForward,Volume2,Plus,Search,Trash2,Headphones,Radio,LogOut,ExternalLink,RefreshCw,ListMusic,AlignLeft} from 'lucide-react';
import {CardBoard,type CardSpec} from './CardBoard';
import {CardActions} from './CardPrimitives';
import {Button,IconButton,Select,Empty,Field,Modal,Avatar} from './ui';
import {state,ui,invoke,perform,account,notify,saveSettings} from './model';
import {community,connect,joinVoice,leaveVoice} from '../../../packages/community/client';
import {music,musicTime,loadMusic,playTrack,toggleMusic,nextTrack,seekMusic,setMusicVolume,shareMusic,removeTrack} from './music-player';
const rooms=[{id:'lobby',name:'旅人休息室'},{id:'survival',name:'原版生存群组'},{id:'mod-1',name:'模组一服'},{id:'mod-2',name:'模组二服'}];

export function MusicMini(){const m=useSnapshot(music);if(!m.current)return null;return <div className="music-mini"><Link to="/music" title={m.current.title}><Music2 size={14}/><span>{m.current.title}</span></Link><IconButton icon={m.playing?Pause:Play} label={m.playing?'暂停音乐':'播放音乐'} disabled={m.loading} onClick={toggleMusic}/><IconButton icon={AlignLeft} label={m.lyricsFloating?'收回歌词':'显示悬浮歌词'} onClick={()=>music.lyricsFloating=!m.lyricsFloating}/></div>;}
export function MusicHost(){const s=useSnapshot(state),loaded=useRef(false);useEffect(()=>{if(!s.ready||loaded.current||!window.launcher)return;loaded.current=true;void (async()=>{if(s.settings.backgroundMusic){await invoke('music.adopt',{url:s.settings.backgroundMusic});await saveSettings({backgroundMusic:''});}await loadMusic();})().catch(()=>{});},[s.ready,s.settings.backgroundMusic]);return <LyricsHost/>;}
export function MusicPage(){
 const s=useSnapshot(state),m=useSnapshot(music),c=useSnapshot(community);
 const [query,setQuery]=useState(''),[results,setResults]=useState<any[]>([]),[searching,setSearching]=useState(false),[error,setError]=useState(''),[room,setRoom]=useState('lobby'),[issues,setIssues]=useState<any[]>([]),[playlistOpen,setPlaylistOpen]=useState(false),[playlistLink,setPlaylistLink]=useState(''),[playlistResult,setPlaylistResult]=useState<any>(null);
 useEffect(()=>{if(!music.ready)void perform(loadMusic);},[]);
 async function search(){if(searching)return;setSearching(true);setError('');try{const input=query.trim(),id=input.match(/(?:id=|^)(\d{1,18})(?:&|$)/)?.[1];if(id){const item=await invoke('music.add',{id});setResults([item]);await loadMusic();}else setResults((await invoke('music.search',{query:input})).items);}catch(e:any){setError(e.message);}finally{setSearching(false);}}
 const cards:CardSpec[]=[
 {id:'lyrics',title:'歌词',w:12,minW:4,x:0,y:39,h:15,minH:12,content:<LyricsCard/>},
  {id:'player',title:'正在播放',w:12,x:0,y:26,h:13,minH:13,minW:6,content:<div className="music-player-card"><div className="music-now"><div className={'music-disc '+(m.playing?'playing':'')}><Music2 size={35}/></div><div><h2>{m.current?.title||'尚未选择音乐'}</h2><p>{m.current?.artist||'导入音乐，或搜索网易云歌曲'}</p><small>{m.loading?'正在准备音频…':c.musicSharing?'正在分享到房间':m.playing?'正在播放':m.current?'已暂停':'未选择曲目'}</small></div></div><div className="music-player-controls"><div className="music-scrubber"><input type="range" aria-label="播放进度" min="0" max={m.duration||1} step=".1" value={Math.min(m.position,m.duration||1)} disabled={!m.duration} onChange={e=>seekMusic(Number(e.target.value))}/><div><span>{musicTime(m.position)}</span><span>{musicTime(m.duration)}</span></div></div><div className="music-transport"><IconButton icon={SkipBack} label="上一首" onClick={()=>nextTrack(-1)} disabled={!m.items.length}/><Button tone="solid" icon={m.playing?Pause:Play} onClick={toggleMusic} disabled={!m.items.length&&!m.current}>{m.loading?'取消等待':m.playing?'暂停':'播放'}</Button><IconButton icon={SkipForward} label="下一首" onClick={()=>nextTrack()} disabled={!m.items.length}/><Select label="播放顺序" value={m.mode} options={[{value:'list',label:'列表循环'},{value:'single',label:'单曲循环'},{value:'shuffle',label:'随机播放'}]} onChange={(value:string)=>music.mode=value}/></div><Field label="本机音量"><div className="music-volume"><Volume2 size={18}/><input type="range" min="0" max="1" step=".02" value={s.settings.musicVolume??.3} onChange={e=>void perform(()=>setMusicVolume(Number(e.target.value)))}/><small>{Math.round((s.settings.musicVolume??.3)*100)}%</small></div></Field>{m.notice&&<p className="music-hint" role="status">{m.notice}</p>}{m.error&&<div className="inline-error">{m.error}<Button onClick={()=>m.current&&playTrack(m.current)}>重试</Button></div>}</div></div>},
  {id:'library',title:'我的音乐',w:6,x:6,y:0,h:26,minH:26,maxH:26,minW:5,content:<><CardActions><Button icon={Plus} onClick={async()=>{const value=await invoke('music.import');await loadMusic();setIssues(value.errors);if(value.items.length)notify(`已导入 ${value.items.length} 首音乐`);}}>导入音乐</Button><Button icon={ListMusic} onClick={()=>{setPlaylistResult(null);setPlaylistOpen(true);}}>导入歌单</Button><Button icon={RefreshCw} onClick={loadMusic}>刷新</Button><span className="muted">{m.items.length} 首</span></CardActions><div className="music-track-list">{m.items.length?m.items.map((t:any)=><div key={t.id} className={'music-track '+(m.current?.id===t.id?'current':'')}><button className="music-track-main" onClick={()=>void playTrack(t)}><Music2 size={18}/><span><strong>{t.title}</strong><small>{t.artist} · {t.source==='netease'?'网易云':t.format?.toUpperCase()||'本地'}</small></span></button><IconButton icon={Trash2} label={'移除 '+t.title} onClick={()=>ui.confirm={title:'从音乐库移除？',message:'仅删除启动器内的副本，原始音乐文件会保留。',action:()=>removeTrack(t.id)}}/></div>):<Empty icon={Music2} title="还没有音乐">导入本地音乐，或添加网易云歌曲与歌单。</Empty>}</div></>},
  {id:'online',title:'网易云音乐',w:6,x:0,y:0,h:13,minH:13,minW:5,content:<><form className="music-search" onSubmit={e=>{e.preventDefault();void search();}}><div className="search"><Search size={17}/><input aria-label="搜索网易云音乐" placeholder="歌名、歌手或网易云歌曲链接" value={query} onChange={e=>setQuery(e.target.value)}/></div><Button type="submit" disabled={searching||!query.trim()}>{searching?'搜索中…':'搜索'}</Button></form>{error&&<p className="inline-error">{error}</p>}<div className="music-track-list">{results.map(t=><div className="music-track" key={t.id}><div className="music-track-main"><Music2 size={18}/><span><strong>{t.title}</strong><small>{t.artist}</small></span></div><IconButton icon={Play} label={'播放 '+t.title} onClick={()=>playTrack(t)}/><IconButton icon={Plus} label={'收藏 '+t.title} onClick={async()=>{await invoke('music.add',{id:t.netId});await loadMusic();notify('已加入我的音乐');}}/></div>)}</div><p className="music-hint">按曲目版权与个人账号权限播放；未登录时使用可用外链。</p><NeteaseAccount/><Button icon={ExternalLink} onClick={()=>invoke('external.open',{url:'https://music.163.com/'})}>打开网易云</Button></>},
  {id:'room',title:'一起听',w:6,x:0,y:13,h:13,minH:13,minW:5,content:<><p className="music-hint">与同一语音房间的伙伴一起听。</p><Field label="选择房间"><Select value={room} onChange={setRoom} options={rooms.map(r=>({value:r.id,label:r.name}))}/></Field><CardActions>{!c.connected?<Button icon={Headphones} onClick={()=>account(s)?connect():ui.dialog='account'}>连接社区</Button>:<Button icon={Headphones} disabled={c.room===room} onClick={()=>joinVoice(room,'',true)}>{c.room===room?'已在这个房间':'加入收听'}</Button>}{c.room&&<Button icon={LogOut} onClick={leaveVoice}>离开房间</Button>}</CardActions>{c.room&&<><p className="music-room-name">{rooms.find(r=>r.id===c.room)?.name} · {c.peers+1} 人</p><div className="music-room-members">{c.users.filter(u=>u.room===c.room).map(u=><span key={u.id}><Avatar name={u.name} size={25}/>{u.name}</span>)}</div><Button tone={c.musicSharing?'':'solid'} icon={Radio} disabled={!m.current} onClick={()=>shareMusic(!c.musicSharing)}>{c.musicSharing?'停止分享音乐':'分享当前播放'}</Button><p className="music-hint">加入收听默认不开麦，语音页可单独开启。离开房间即停止分享。</p></>}{c.voiceError&&<p className="inline-error">{c.voiceError}</p>}</>}
 ];
 return <div className="standard-page music-page"><div className="workspace-top"><h1>音乐</h1><span className="muted">播放、收藏，一起听</span></div><CardBoard id="music" label="音乐卡片" cards={cards}/><Modal open={playlistOpen} title="导入网易云歌单" onClose={()=>setPlaylistOpen(false)}><Field label="歌单链接或 ID" hint="仅导入公开歌单的曲目，播放时再准备音频。已有歌曲自动跳过。"><input autoFocus value={playlistLink} placeholder="https://music.163.com/playlist?id=…" onChange={e=>setPlaylistLink(e.target.value)}/></Field>{playlistResult&&<div className="playlist-result" role="status"><strong>{playlistResult.name}</strong><p>已加入 {playlistResult.added} 首 · 已有 {playlistResult.duplicates} 首</p>{!!(playlistResult.unavailable+playlistResult.unlisted)&&<p>有 {playlistResult.unavailable+playlistResult.unlisted} 首曲目暂时不可读取。</p>}{!!playlistResult.limited&&<p>音乐库上限 500 首，剩余 {playlistResult.limited} 首未导入。</p>}</div>}<footer className="modal-actions"><Button onClick={()=>setPlaylistOpen(false)}>{playlistResult?'完成':'取消'}</Button><Button tone="solid" disabled={!playlistLink.trim()} onClick={async()=>{setPlaylistResult(null);const value=await invoke('music.playlist',{link:playlistLink});await loadMusic();setPlaylistResult(value);}}>导入歌单</Button></footer></Modal><Modal open={issues.length>0} title="部分音乐未能导入" onClose={()=>setIssues([])}><div className="music-import-errors">{issues.map((v,i)=><div key={i}><strong>{v.file}</strong><p>{v.error}</p></div>)}</div><Button onClick={()=>setIssues([])}>知道了</Button></Modal></div>;
}
