import {HxzUpdate} from './HxzUpdate';
import {FloatingLyrics} from './Lyrics';
import {InboxButton} from './Inbox';
import {MusicPage,MusicMini,MusicHost} from './Music';
import {PageBoundary} from './PageBoundary';
import {useEffect,useLayoutEffect,useState,useRef,lazy,Suspense} from 'react';
import {useSnapshot} from 'valtio';
import {HashRouter,Routes,Route,NavLink,useLocation,useNavigate} from 'react-router-dom';
import {MotionConfig,motion,AnimatePresence,useReducedMotion} from 'motion/react';
import {Search,Minus,Square,X,Layers,ArrowUpRight,Play,MessagesSquare,Gamepad2,Check,AlertCircle,Settings,Sparkles,ShoppingBag,Download,Box,Music2,MoreHorizontal,Palette,PanelTop,UserRound,Network} from 'lucide-react';
import {state,ui,task,account,desktop,reload,perform,invoke,saveSettings,importPack,selectInstance} from './model';
import {community,connect} from '../../../packages/community/client';
import {Home} from './HomeDashboard';
import {GameLibrary} from './GameLibrary';
import {normalizeCardStyle} from '../../../packages/engine/core/card-layout.mjs';
import {Dialogs,TaskDrawer} from './Dialogs';
import {Button,IconButton,Avatar,Modal,Dropdown,Toggle} from './ui';
const MultiplayerPage=lazy(()=>import('./Multiplayer').then(m=>({default:m.MultiplayerPage})));
const Linking=lazy(()=>import('./Linking').then(m=>({default:m.Linking})));
const CommunityPage=lazy(()=>import('./Community').then(m=>({default:m.CommunityPage})));
const Workshop=lazy(()=>import('./Workshop').then(m=>({default:m.Workshop})));
const ArcadePage=lazy(()=>import('./Arcade').then(m=>({default:m.ArcadePage})));
const SettingsPage=lazy(()=>import('./Settings').then(m=>({default:m.SettingsPage})));
const AccountPage=lazy(()=>import('./AccountCards').then(m=>({default:m.AccountPage})));
function Shell(){
 const s=useSnapshot(state),u=useSnapshot(ui),t=useSnapshot(task),c=useSnapshot(community),location=useLocation(),rawNavigate=useNavigate();
 const [command,setCommand]=useState(false),[query,setQuery]=useState(''),[destination,setDestination]=useState(''),[compactNav,setCompactNav]=useState(false);const nav=useRef<HTMLElement>(null);
 const taps=useRef<number[]>([]),reduce=useReducedMotion(),video=useRef<HTMLVideoElement>(null),main=useRef<HTMLElement>(null);
 // The page viewport resets independently of nested chat history/card scroll areas.
 useLayoutEffect(()=>{if(main.current)main.current.scrollTop=0;},[location.pathname]);
 const speed=s.settings.animationSpeed??1,off=speed===0||!!reduce;
 const navigate=(path:string)=>{if((ui.unsaved||ui.layoutUnsaved)&&location.pathname!==path)setDestination(path);else rawNavigate(path);};
 const discover=()=>{const now=Date.now();taps.current=[...taps.current.filter(v=>now-v<2500),now];if(taps.current.length>=5){taps.current=[];navigate('/linking');}};
 useEffect(()=>{const capture=(e:MouseEvent)=>{const link=(e.target as Element)?.closest('a');if((!ui.unsaved&&!ui.layoutUnsaved)||!link||e.ctrlKey||e.metaKey||link.target==='_blank')return;const url=new URL(link.href,window.location.href);if(url.origin===window.location.origin&&url.hash.startsWith('#/')&&url.hash.slice(1)!==location.pathname){e.preventDefault();e.stopPropagation();setDestination(url.hash.slice(1));}};document.addEventListener('click',capture,true);return()=>document.removeEventListener('click',capture,true);},[location.pathname]);
 useEffect(()=>{const visibility=()=>{if(document.hidden)video.current?.pause();else void video.current?.play().catch(()=>{});};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[]);
 useEffect(()=>{void perform(reload).then(()=>{if(state.settings.selectedAccount)void connect();});const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommand(v=>!v);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{
  const root=document.documentElement;root.dataset.theme=s.settings.theme;root.dataset.motion=off?'off':'on';root.style.setProperty('--duration',off?'0s':(.32/speed)+'s');root.style.setProperty('--accent',s.settings.accentColor||'#5668bc');root.style.setProperty('--font-size',(s.settings.fontSize||16)+'px');
  const rgba=(hex:string,alpha:number)=>`rgba(${hex.slice(1).match(/../g)?.map(v=>parseInt(v,16)).join(',')||'255,255,255'},${Math.max(.2,Math.min(1,alpha))})`;
  const base=s.settings.theme==='dark'?'#252a35':'#ffffff';
  for(const [key,value] of Object.entries(s.settings.columns||{}) as any)root.style.setProperty('--'+key+'-surface',rgba(value.color||base,value.opacity??1));
  const card=normalizeCardStyle(s.settings.cardStyle),workspace=s.settings.columns?.workspace;
  root.style.setProperty('--card-surface',rgba(card.color||workspace?.color||base,card.opacity));root.style.setProperty('--card-radius',card.radius+'px');
 },[s.settings.theme,s.settings.fontSize,s.settings.accentColor,s.settings.columns,s.settings.cardStyle,speed,off]);
 const hidden=s.settings.hiddenLinks||[];
 const primary=[{to:'/',name:'游戏',icon:Play},{to:'/multiplayer',name:'联机',icon:Network},{to:'/workshop',name:'资源',icon:Download},{to:'/community',name:'社区',icon:MessagesSquare},{to:'/settings',name:'设置',icon:Settings}].filter(n=>!hidden.includes(n.to));
 const extra=[{to:'/library',name:'所有实例',icon:Box},{to:'/arcade',name:'小游戏',icon:Gamepad2},{to:'/arcade/shop',name:'积分商城',icon:ShoppingBag},{to:'/music',name:'音乐播放器',icon:Music2},{to:'/account',name:'账号与积分',icon:UserRound},...(s.settings.showLinking?[{to:'/linking',name:'Linking',icon:Sparkles}]:[])].filter(n=>!hidden.includes(n.to));
 const pinned=s.settings.pinnedLinks||[],overflow=extra.filter(n=>!pinned.includes(n.to)),mainNav=[...primary.filter(n=>n.to!=='/settings'),...pinned.map((to:string)=>extra.find(n=>n.to===to)).filter(Boolean),...primary.filter(n=>n.to==='/settings')];
 const routeActive=(to:string)=>to==='/'?location.pathname==='/'||location.pathname==='/library'&&!pinned.includes('/library'):to==='/arcade'?location.pathname.startsWith('/arcade')&&!location.pathname.startsWith('/arcade/shop'):location.pathname===to||location.pathname.startsWith(to+'/');
 useEffect(()=>{const el=nav.current;if(!el)return;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');const measure=()=>{if(!ctx)return;const item=el.querySelector('a');if(!item)return;ctx.font=getComputedStyle(item).font;const needed=mainNav.reduce((sum:number,n:any)=>sum+ctx.measureText(n.name).width+54,0)+(mainNav.length+1)*5+85;setCompactNav(needed>el.clientWidth);};const observer=new ResizeObserver(measure);observer.observe(el);measure();return()=>observer.disconnect();},[mainNav.map((n:any)=>n.to).join('|'),s.settings.fontSize]);
 const commands=[...primary,...extra,...(s.settings.linkingDiscovered&&!extra.some(n=>n.to==='/linking')?[{to:'/linking',name:'Linking',icon:Sparkles}]:[]),...s.instances.map((i:any)=>({to:'/',name:i.name,instance:i.id}))].filter(i=>i.name.toLowerCase().includes(query.toLowerCase()));
 return <MotionConfig reducedMotion={off?'always':'user'} transition={{duration:off?0:.28/speed,ease:[.22,.68,.24,1]}}><div className={'app-shell air-shell '+(s.settings.backgroundImage||s.settings.backgroundVideo?'has-background':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={e=>{if(!e.dataTransfer.types.includes('Files'))return;e.preventDefault();const file=e.dataTransfer.files[0];if(file&&!u.dialog)void perform(()=>importPack(file));}}>
  {s.settings.backgroundVideo?<video ref={video} className="app-background" src={s.settings.backgroundVideo} muted autoPlay loop playsInline style={{opacity:s.settings.backgroundOpacity,objectPosition:`${s.settings.backgroundPositionX??50}% ${s.settings.backgroundPositionY??50}%`}}/>:s.settings.backgroundImage?<img className="app-background" src={s.settings.backgroundImage} alt="" style={{opacity:s.settings.backgroundOpacity,objectPosition:`${s.settings.backgroundPositionX??50}% ${s.settings.backgroundPositionY??50}%`}}/>:null}<MusicHost/>
  <header className="air-titlebar"><button className="air-brand" onClick={discover} title="幻想镇 NEXT"><span>幻</span><div><strong>幻想镇</strong><small>FANTASY TOWN</small></div></button><nav ref={nav} className={"air-primary-nav "+(compactNav?"nav-compact":"")} aria-label="主导航">{mainNav.map((n:any)=><NavLink key={n.to} to={n.to} title={n.name} aria-label={n.name} end={n.to==='/'} onContextMenu={e=>{e.preventDefault();ui.navigation=true;}} className={()=>routeActive(n.to)?'active':''}><n.icon size={17}/><span>{n.name}</span></NavLink>)}<Dropdown trigger={<button className={overflow.some(n=>n.to!=='/library'&&routeActive(n.to))?'active':''}><MoreHorizontal size={18}/>更多</button>} items={[...overflow.map(n=>({label:n.name,icon:n.icon,action:()=>navigate(n.to)})),{separator:true},{label:'整理主导航',icon:PanelTop,action:()=>ui.navigation=true}]}/></nav><div className="air-window-tools"><InboxButton/><IconButton icon={Search} label="搜索功能 · Ctrl K" onClick={()=>setCommand(true)}/><button className="air-avatar" title="账号与角色" onClick={()=>navigate('/account')}><Avatar name={account(s)?.name} image={account(s)?.avatar} size={29}/></button><span/><IconButton icon={Minus} label="最小化" onClick={()=>invoke('window.control',{action:'minimize'})}/><IconButton icon={Square} label="最大化" onClick={()=>invoke('window.control',{action:'maximize'})}/><IconButton icon={X} label="关闭" className="close-window" onClick={()=>invoke('window.control',{action:'close'})}/></div></header>
  {!desktop&&<div className="preview-notice">界面预览 · 登录、游戏和实时数据请使用桌面程序</div>}
  <main ref={main} className="app-main">{s.error?<div className="startup-error"><AlertCircle/><h2>读取本机配置失败</h2><p>{s.error}</p><Button onClick={reload}>重试</Button></div>:!s.ready?<div className="loading-page">正在准备你的游戏库…</div>:<AnimatePresence mode="wait" initial={false}><motion.div key={location.pathname.split('/')[1]} className="page-transition" initial={{opacity:0,y:off?0:5}} animate={{opacity:1,y:0}} exit={{opacity:0,y:off?0:-3}}><PageBoundary key={location.pathname}><Suspense fallback={<div className="loading-page">正在打开…</div>}><Routes><Route path="/" element={<Home/>}/><Route path="/library" element={<GameLibrary/>}/><Route path="/multiplayer" element={<MultiplayerPage/>}/><Route path="/community/*" element={<CommunityPage/>}/><Route path="/workshop/*" element={<Workshop/>}/><Route path="/arcade/*" element={<ArcadePage/>}/><Route path="/account/*" element={<AccountPage/>}/><Route path="/linking" element={<Linking/>}/><Route path="/music" element={<MusicPage/>}/><Route path="/settings/*" element={<SettingsPage/>}/></Routes></Suspense></PageBoundary></motion.div></AnimatePresence>}</main>
  <footer className="app-status"><MusicMini/><span><i className={c.connected?'connected':''}/>{c.status}</span>{c.room&&<span>语音已连接 · {c.room}</span>}<button onClick={()=>ui.tasks=true}><Layers size={13}/>{t.busy?t.phase:'任务与日志'}</button><small>0.6.3</small></footer>
  <FloatingLyrics/><HxzUpdate/><TaskDrawer/><Dialogs/><AnimatePresence>{u.toast&&<motion.div className={'toast '+(u.toastError?'error':'')} role="status" initial={{opacity:0,y:off?0:10}} animate={{opacity:1,y:0}} exit={{opacity:0}}>{u.toastError?<AlertCircle size={18}/>:<Check size={18}/>}<span>{u.toast}</span><IconButton icon={X} label="关闭提示" onClick={()=>ui.toast=''}/></motion.div>}</AnimatePresence>
<Modal open={!!u.navigation} onClose={()=>ui.navigation=false} title="整理主导航" description="开启后放到顶部主栏，关闭后收回更多。右键主栏入口也能整理。"><div className="navigation-options">{extra.map(n=><Toggle key={n.to} label={n.name} description={pinned.includes(n.to)?'已在主栏':'收纳在更多'} checked={pinned.includes(n.to)} onChange={(on:boolean)=>saveSettings((settings:any)=>({pinnedLinks:on?[...new Set([...(settings.pinnedLinks||[]),n.to])]:(settings.pinnedLinks||[]).filter((to:string)=>to!==n.to)}))}/>)}</div><footer className="modal-actions"><Button onClick={()=>saveSettings({pinnedLinks:[]})}>恢复默认导航</Button><Button tone="solid" onClick={()=>ui.navigation=false}>完成</Button></footer></Modal>
  <Modal open={command} onClose={()=>setCommand(false)} title="快速前往"><div className="search"><Search size={18}/><input autoFocus placeholder="搜索功能或游戏" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>Ctrl K</kbd></div><div className="command-list">{commands.map((item:any)=><button key={item.name} onClick={()=>perform(async()=>{if(item.instance)await selectInstance(item.instance);navigate(item.to);setCommand(false);})}><span>{item.name}</span><ArrowUpRight size={17}/></button>)}</div></Modal>
  <Modal open={!!destination} title="应用尚未保存的更改？" onClose={()=>setDestination('')}><p>可以保存后离开，或放弃本次更改。</p><footer className="modal-actions"><Button onClick={()=>setDestination('')}>继续编辑</Button><Button onClick={()=>{const pending=[ui.unsaved,ui.layoutUnsaved];for(const change of pending)change?.discard();ui.unsaved=null;ui.layoutUnsaved=null;rawNavigate(destination);setDestination('');}}>放弃更改</Button><Button tone="solid" onClick={async()=>{const pending=[ui.unsaved,ui.layoutUnsaved];for(const change of pending)await change?.save();ui.unsaved=null;ui.layoutUnsaved=null;rawNavigate(destination);setDestination('');}}>保存并离开</Button></footer></Modal>
 </div></MotionConfig>;
}
export default function App(){return <HashRouter><Shell/></HashRouter>;}
