import React,{useState} from 'react';import * as Dialog from '@radix-ui/react-dialog';import * as Menu from '@radix-ui/react-dropdown-menu';import {X,ChevronDown,Check,LoaderCircle,ArrowUpRight} from 'lucide-react';import {perform,notify} from './model';
export function Button({children,icon:Icon,onClick,tone='',className='',disabled=false,...props}:any){const [busy,setBusy]=useState(false);return <button {...props} disabled={disabled||busy} className={`button ${tone} ${className}`} onClick={async e=>{if(!onClick)return;setBusy(true);try{await onClick(e);}catch(error:any){notify(error.message||String(error),true);}finally{setBusy(false);}}}>{busy?<LoaderCircle className="spin" size={17}/>:Icon?<Icon size={17}/>:null}{children}</button>}
export function IconButton({icon:Icon,label,...props}:any){return <Button {...props} className={'icon-button '+(props.className||'')} icon={Icon} title={label} aria-label={label}/>}
export function Modal({open,onClose,title,children,wide=false,description}:any){return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose?.()}><Dialog.Portal><Dialog.Overlay className="modal-backdrop"/><Dialog.Content className={'modal '+(wide?'wide':'')} aria-describedby={description?'modal-description':undefined}><header><div><Dialog.Title>{title}</Dialog.Title>{description&&<Dialog.Description id="modal-description">{description}</Dialog.Description>}</div><Dialog.Close asChild><IconButton icon={X} label="关闭"/></Dialog.Close></header><div className="modal-body">{children}</div></Dialog.Content></Dialog.Portal></Dialog.Root>}
export function Select({value,onChange,options,label,disabled=false}:any){
 const selected=options.find((o:any)=>String(o.value??o)===String(value));
 const text=selected?.label??selected??value??'请选择';
 return <Menu.Root><Menu.Trigger className="select" disabled={disabled} aria-label={label} title={String(text)}><span className="select-label">{text}</span><ChevronDown size={15}/></Menu.Trigger><Menu.Portal><Menu.Content className="menu select-menu" align="start" sideOffset={5} collisionPadding={12}><Menu.RadioGroup value={String(value??'')} onValueChange={v=>void perform(()=>onChange(options.find((o:any)=>String(o.value??o)===v)?.value??v))}>{options.map((o:any)=><Menu.RadioItem className="menu-item" key={String(o.value??o)} value={String(o.value??o)}><span className="menu-label">{o.label??o}</span><Menu.ItemIndicator className="menu-check"><Check size={14}/></Menu.ItemIndicator></Menu.RadioItem>)}</Menu.RadioGroup></Menu.Content></Menu.Portal></Menu.Root>;
}
export function Dropdown({trigger,items}:any){return <Menu.Root><Menu.Trigger asChild>{trigger}</Menu.Trigger><Menu.Portal><Menu.Content className="menu" sideOffset={5} collisionPadding={12}>{items.map((i:any,n:number)=>{
 if(i.separator)return <Menu.Separator className="menu-separator" key={n}/>;
 const content=<>{i.icon&&<i.icon size={16}/>}<span className="menu-label">{i.label}</span>{i.detail&&<small>{i.detail}</small>}</>;
 return typeof i.checked==='boolean'?<Menu.CheckboxItem key={i.label} className="menu-item" checked={i.checked} disabled={i.disabled} onCheckedChange={()=>void perform(i.action)}>{content}<Menu.ItemIndicator className="menu-check"><Check size={14}/></Menu.ItemIndicator></Menu.CheckboxItem>:<Menu.Item key={i.label} className={'menu-item '+(i.danger?'danger':'')} disabled={i.disabled} onSelect={()=>void perform(i.action)}>{content}</Menu.Item>;
 })}</Menu.Content></Menu.Portal></Menu.Root>}
export function Toggle({checked,onChange,label,description,disabled=false}:any){return <label className="toggle-row"><span><strong>{label}</strong>{description&&<small>{description}</small>}</span><button role="switch" aria-checked={checked} aria-label={label} disabled={disabled} onClick={()=>void perform(()=>onChange(!checked))} className={'toggle '+(checked?'on':'')}><i/></button></label>}
export function Field({label,hint,children}:any){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Empty({icon:Icon,title,children,action}:any){return <div className="empty">{Icon&&<Icon size={35} strokeWidth={1.4}/>}<h3>{title}</h3>{children&&<p>{children}</p>}{action}</div>}
export function PageTitle({eyebrow,title,children,actions}:any){return <header className="page-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{children&&<p>{children}</p>}</div><div className="actions">{actions}</div></header>}
export function Avatar({name='',image,size=32}:any){return <span className="avatar" style={{width:size,height:size}}>{image?<img src={image} alt=""/>:(name?.slice(0,1)||'旅')}</span>}
export function Segments({value,onChange,items}:any){return <div className="segments">{items.map((i:any)=><button key={i.id} aria-pressed={value===i.id} className={value===i.id?'selected':''} onClick={()=>onChange(i.id)}>{i.icon&&<i.icon size={16}/>}<span>{i.label}</span>{i.count!=null&&<small>{i.count}</small>}</button>)}</div>}
export const date=(n:any)=>new Date(n).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
